### ISSUE TITLE
Add total size/count to size and request content type charts

### ISSUE THREAD

**Issue by zeman** [SpeedCurve-Metrics/SpeedCurve#1]
![screen shot 2015-06-12 at 12 36 42 pm](https://cloud.githubusercontent.com/assets/204268/8121431/b8bd209a-10ff-11e5-8a2e-895aa0797d18.png)

Currently the trending charts showing size and assets don't show the total size/count across all content types.

Things to add:

* First total size/count in time series
* Most recent total size/count in time series
* Percentage of change over the selected timespan
* Could also do the 3 metrics above for each content type in an expandable area

**Comment by lostthetrail** [comment]
Having the total page weight for a single page is invaluable.

It could also be interesting to be able to click on a single point in time in the graph above and get a pie chart showing the distribution of those assets in that total page weight.

**Comment by zeman** [comment]
You can click on any point and go through to the test/waterfall page. At the bottom you get a breadown of content like so:

![screen shot 2015-06-12 at 2 02 07 pm](https://cloud.githubusercontent.com/assets/204268/8122287/d10fbd72-110b-11e5-8010-ce0d0aec79c8.png)

Is that what you're looking for? Did you want that in the tooltip?

**Comment by lostthetrail** [comment]
That breakdown is what I was suggesting in the second part. Thanks for reminding me that exists.

**Comment by stevesouders** [comment]
Doing "total" on a stacked chart is hard. Could do a vertical line at the current X-axis point. If you hover in that vertical line ABOVE the stack, then it shows total.
