### ISSUE TITLE
View HTTP Request involved in 3rd party screen

### ISSUE THREAD

**Issue by kennydee** [SpeedCurve-Metrics/SpeedCurve#10]
Hi,

The concatenation of 3rd party is a really great feature, but for digging into one 3rd party issue, it would be very usefull to see each HTTP Request involved for each 3rd party line.
I know that we could go the full waterfall page searching for request, but it's not that simple to find out those request in a big waterfall, and it will be better to have directly access to the request (and timing information) on the 3rd party page below this line : 
![third_party___speedcurve](https://cloud.githubusercontent.com/assets/1484406/8324505/87d9c37e-1a51-11e5-8957-8064e00d1b72.png)

Thanks

**Comment by zeman** [comment]
Thanks, couldn't agree more. This is on our todo list!

**Comment by josephwynn-sc** [comment]
I'm happy to close this issue as "done" now that SpeedCurve has the new Third Party dasboard. Sometimes good things take time :)
