### ISSUE TITLE
History may move to new entry when adding URLs

### ISSUE THREAD

**Issue by driis** [SpeedCurve-Metrics/SpeedCurve#102]
I had a site with some existing checks. I wanted to add a repeat view check; so I added an URL and typed in the URL that already existed, then used the "Repeat View" template to add a script to the page. I gave this check another label. After clicking "Save", I saw to my horror that history was gone from the old check and had moved to the new, repeat view, check.

If this had gone unnoticed before the checks ran, I would have gotten mixed data from the old and new check into the same graph 👎 

If it's not allowed to have duplicate URL's, then the site should validate against it. It was intuitive for me to add the same URL again and choosing "Repeat View", and no warning lights blinked.

**Comment by zeman** [comment]
Sorry about this bug. As you discovered URLs do need to be unique within a site. We'll add some validation to highlight the duplicates.

Note that if you are adding scripts then the URL in the "navigate" commands are what actually get tested. This allows you to make the URL in URL field whatever you like as it won't be the URL tested. So if adding a repeat view you could make the URL "http://website.com/?repeat-view" while "http://website.com/" is what gets tested via the script.

**Comment by driis** [comment]
Yes, I figured out that the URL wasn't important when using a script, so I could work around the bug, and I event got the old history back to the right label again by deleting the newly created ones and creating them again, renaming their labels.

**Comment by zeman** [comment]
We now allow duplicate URLs within a site which sorts out these overwriting issues. You also no longer need to hack the URL to make it unique when testing different scripts on the same URL.
