### ISSUE TITLE
API can return duplicate URLs

### ISSUE THREAD

**Issue by driis** [SpeedCurve-Metrics/SpeedCurve#103]
When accessing https://api.speedcurve.com/v1/urls, I can get duplicated URLs (Same label and url, different url_id). In the UI, these duplicated urls cannot be seen.

For Site ID 4496, the urls for "DK Home", "DK VIP" and "DK Search" appears 3 times.

I have a feeling this could be related to https://github.com/SpeedCurve-Metrics/SpeedCurve/issues/102

**Comment by zeman** [comment]
You were seeing deleted URLs via the API. We've now filtered these out so only active URLs are visible.
