### ISSUE TITLE
Allow video comparison between two test results

### ISSUE THREAD

**Issue by iamnmtd** [SpeedCurve-Metrics/SpeedCurve#105]
Making it easy to use the WPT video comparison feature between two test results would be a great enhancement - currently its possible to generate the URL manually to get the result but would be good to have this integrated in the tool. I know HAR comparison is hard, but the WPT video comparison does give a HAR overlay display which can help to see the position where waterfalls diverge leading to identification of potential problem assets and 3rd parties.

**Comment by stevesouders** [comment]
The hard part here is providing a UI to choose the two tests. How would you want to specify the two tests to compare?

**Comment by stevesouders** [comment]
Add a "Compare" option in the test point popup menu that contains "View Test" and "Add Note". Then perhaps that FIRST test point is highlighted while the user then goes to identify the SECOND test point from the *same* chart. (Not sure if we'd support comparing tests across DIFFERENT charts.)

**Comment by stevesouders** [comment]
Maybe we could also initiate this from the Test Results page so we COULD compare tests across different dashboards and Sites.

**Comment by stevesouders** [comment]
In the interim, here's how to generate the side-by-side video URL manually:

1. In SpeedCurve, go to the first test you want to compare. The URL has this format:
    https://speedcurve.com/<ORGNAME>/<TEAMNAME>/test/<TESTID>/
Copy the TESTID from that URL. It looks like this: 170407_KA_06e1a14c32f08c2cd9e306dffc3fc49d.

2. Go to the second test you want to compare and get its TESTID, e.g., 170411_SN_170d34904a9781ce9aa3d93bf4c6a9d7.

3. Create the video comparison URL with this format:
    http://wpt.speedcurve.com/video/compare.php?tests=TESTID1,TESTID2[,...]
For example:
    http://wpt.speedcurve.com/video/compare.php?tests=170407_KA_06e1a14c32f08c2cd9e306dffc3fc49d,170411_SN_170d34904a9781ce9aa3d93bf4c6a9d7

4. Load the compare URL and click on the "Create Video" button to create the side-by-side video.

**Comment by zeman** [comment]
We've now made this a little easier by letting you compare any test ids on the Deploy dashboard.

https://support.speedcurve.com/using-synthetic/compare-metrics-filmstrips-video-for-any-two-tests
