### ISSUE TITLE
Be able to specify order of display for Sites and URL's

### ISSUE THREAD

**Issue by iamnmtd** [SpeedCurve-Metrics/SpeedCurve#106]
Currently, if a user wants to specifically order Sites and URL's in the UI you have to prefix the labels with numbers to make them sort alphabetically as you want. It would be good to be able to fix this order 'behind the scenes' so to speak.

**Comment by stevesouders** [comment]
Which dashboard are you thinking about where specifying the order would make the dashboard easier to use?

**Comment by stevesouders** [comment]
Order of Sites isn't such a big issue now that SpeedCurve remembers your most recent Site selection across teams. But the order of the URLs is important to reflect the flow through the website, eg, you always start with "Home" and then might go to an "Article" - so it would be better to list them in that order: Home, Article.

**Comment by stevesouders** [comment]
Not sure there's a strong case for making this change. If anyone else has scenarios where the order is important please add a comment.
