### ISSUE TITLE
Being able to set a custom date range for charts

### ISSUE THREAD

**Issue by iamnmtd** [SpeedCurve-Metrics/SpeedCurve#107]
Allow specification of a custom date range for charts alongside the options for

7 DAYS
2 WEEKS
1 MONTH
3 MONTHS
6 MONTHS
LAST YEAR

**Comment by stevesouders** [comment]
We have the zoom in feature which is easier than a "start date" and "end date" widget. What's the context that specifying those date ranges is easier/better than the zoom feature?

**Comment by stevesouders** [comment]
Zoom in only affects the top chart. If it affected ALL charts that would be a good alternative.

**Comment by zeman** [comment]
We've now added a custom option with date pickers for start and end dates.
