### ISSUE TITLE
User Management improvements

### ISSUE THREAD

**Issue by iamnmtd** [SpeedCurve-Metrics/SpeedCurve#108]
- Check - For people with view permissions - don't allow Deploy tests - admins cannot control the resulting check budget usage.
- Check - Don't show features that require full permissions to users that are read only - eg Add Note
- User management - Multi-team/All Teams "view only" users / Make it easier to allocate same person to multiple teams.
- In the team users display - show the date/time a user last logged in / be able to audit a users usage
- OKTA integration for user accounts

**Comment by stevesouders** [comment]
1. Agree that people with view permissions should NOT be able to deploy tests.
2. Unsure about hiding features - that confuses users. We think it's better to show the user an error message if they want to try a feature that they don't have permissions for.
3. Right now it's not that hard to add a user to multiple teams. How would you want it to be easier?
4. What do you mean by "audit"?
5. We're unlikely to do OKTA integration but we can add it to the list.

**Comment by stevesouders** [comment]
3. It IS tedious if you have a lot of teams to add the same person to EVERY team. A quick solution would be to add a person as a "read only" admin at the Org level. 
4. We'd really need to track the last access time for every user at the team & org level, and show this on the Team Users page. 
5. OKTA would make the ACL stuff much easier. Break this out as a separate bug in the repo and see if people add support for it.

**Comment by stevesouders** [comment]
Created separate bugs for 1, 3 & 5. We're not going to do 2 & 4.
