### ISSUE TITLE
Domains should be set per Site not per Team

### ISSUE THREAD

**Issue by iamnmtd** [SpeedCurve-Metrics/SpeedCurve#109]
It doesn't seem logical to me that first party domains are set per team. Within a team I may have more than one of my own sites that do not share domains.

Putting first party domians for multiple sites in a single list can lead to confusion.

**Comment by stevesouders** [comment]
We should clarify that for every test, the domain of the test URL is automatically considered "first party" even if it's NOT specified. Does this change this request?

**Comment by stevesouders** [comment]
Everything works as desired. The main issue is it's confusing.
