### ISSUE TITLE
Shareable links to expire after n days.

### ISSUE THREAD

**Issue by iamnmtd** [SpeedCurve-Metrics/SpeedCurve#110]
Do shareable links to expire after n days or do they live forever? If the latter it would be good to be able to expire them.

**Comment by stevesouders** [comment]
How would you like to control the expiration?

**Comment by stevesouders** [comment]
Add a select list in the "share url" widget to expire after N days.

**Comment by stevesouders** [comment]
In the meantime - if you need to expire a shareable link just ping us and we can rotate your share key.
