### ISSUE TITLE
Duplication of Device and Server Selection

### ISSUE THREAD

**Issue by ricriley** [SpeedCurve-Metrics/SpeedCurve#114]
I don't know if this issue is specific to my account but over the last few days I keep getting a huge duplication of the device and server selections on the benchmarking page.

Please find image attached:
![image](https://cloud.githubusercontent.com/assets/3758651/18509746/1ed6bc1a-7a72-11e6-9a26-bbc3718f686f.png)

Regards,
Ric Riley

**Comment by zeman** [comment]
Thanks for reporting that! Fixed.
