### ISSUE TITLE
Multiple Labels

### ISSUE THREAD

**Issue by flatiron32** [SpeedCurve-Metrics/SpeedCurve#116]
I would like to be able to assign multiple labels to a URL. For instance i have 3 types of pages (T1, T2, T3) used for 4 different product types (P1, P2, P3, P4). I would like to enter the 12 URLs with the appropriate combination of labels and then be able to compare the results by a single label.

**Comment by flatiron32** [comment]
Our business leaders reiterated the desire to have this to allow multiple comparisons of the same tests in different groups.

**Comment by josephwynn-sc** [comment]
We're reviewing our public issues as a team and have decided to close this ticket. SpeedCurve's Synthetic product isn't really set up to handle segmenting like this. You can achieve this sort of segmentation in SpeedCurve LUX using custom data (with the `LUX.addData('template', 'T1')`) and custom charts in Favorites.
