### ISSUE TITLE
Open ended single quote in deploy notes break results page

### ISSUE THREAD

**Issue by evilantnie** [SpeedCurve-Metrics/SpeedCurve#12]
When posting to the deploy endpoint in your API if 
the note parameter leaves an open ended single quote you'll get a parse error 
and the deploy page will not render results after all the tests have run. 
You can recreate the problematic deploy w/ the following curl command:

```
curl "https://api.speedcurve.com/v1/deploy" -u <key>:x --request POST --data note=I%27m%20a%20quote
```

After the tests have completed, you won't be able to render the /deploy page, the javascript console displays the following error:

    XHR finished loading: GET "https://speedcurve.com/deploy-data.php?site=1749&sitename=RealSelf&siteorde…ion=us-west-1&metric=loaded&zoneoffset=-25200&timezone=America/Los_Angeles".
    nrWrapper @ (index):6
    ee.ajaxTransport.Y.cors.e.crossDomain.send @ speedcurve-combined.70.js:3
    ee.extend.ajax @ speedcurve-combined.70.js:3
    onGo @ (index):1361
    (anonymous function) @ (index):1550
    ee.Callbacks.c  @ speedcurve-combined.70.js:2
    ee.Callbacks.d.fireWith  @ speedcurve-combined.70.js:2
    ee.extend.ready @ speedcurve-combined.70.js:2
    a  @ speedcurve-combined.70.js:1
    nrWrapper @ (index):6
    (index):1369 

    Request failed: parsererror

You can fix it by going into the settings to edit the note and removing the quote.

**Comment by zeman** [comment]
This has been fixed for a while now. Let me know if you hit any issues like this again.
