### ISSUE TITLE
Favourite dashboard private link does not show charts

### ISSUE THREAD

**Issue by gtrufitt** [SpeedCurve-Metrics/SpeedCurve#120]
I added a few charts to the new favourite dashboard feature (cool!) and tried to share it:

![image](https://cloud.githubusercontent.com/assets/638051/19111136/cff3ad3a-8af5-11e6-9811-f64b16af565f.png)

but you can't see this dashboard if you're not logged in:

![image](https://cloud.githubusercontent.com/assets/638051/19111174/05a17750-8af6-11e6-8bcf-5814bee189ba.png)

But can still access all the other dashboards across the top tabs. 

Is this user specific which is why you would need to log in? I'd love to be able to share this page to others without them having to log in like the other pages.

**Comment by zeman** [comment]
Yes the new favorite charts are user specific. If you want to share them with other members of the team or via the share links then tick the "Share with team" option.
