### ISSUE TITLE
Date Tokenization

### ISSUE THREAD

**Issue by flatiron32** [SpeedCurve-Metrics/SpeedCurve#121]
It would be very valuable to us if there were a way to build a URL to be tested. For instance, most of our URL have dates in them because our industry and site is highly date driven. It would be great if we could insert a token like %today+90|MM/dd/yyyy% that would insert the date 90 days out formatted to MM/dd/yyyy. 
Right now I will need to update dozens of URLs before December 1st and the underlying search and availably will likely change as we get closer to that date. Or expose a page publicly whose only purpose is to generate these URLs for me.
With this feature I could create URLs or build WPT scripts like 
`navigate https://www.mysite.com/search?from=%today+90|MM/dd/yyyy%&to=%today+97|MM/dd/yyyy%`

My expectation is that these tokens would be available for arbitrary use in WPT scripts.

**Comment by zeman** [comment]
It's a more generic approach but you can currently use the [/settings](https://api.speedcurve.com/#import-settings) endpoint of the API to programmatically update URLs. I'd suggest creating your own script to update the URLs as often as you like.
