### ISSUE TITLE
Tokens

### ISSUE THREAD

**Issue by flatiron32** [SpeedCurve-Metrics/SpeedCurve#122]
It would be valuable for me to be able to create a set of tokens used in all URLs configured. Most of our URLs are for searches that I want to be for the same things everywhere. For instance the same airport code should be used in all URLs. If I could set AIRPORT_CODE = SFO in a token section and then reference it in URLs and WPT scripts it would save a lot of URL upkeep time.

**Comment by zeman** [comment]
It's a more generic approach but you can currently use the [/settings](https://api.speedcurve.com/#import-settings) endpoint of the API to programmatically update URLs. I'd suggest creating your own script to update the URLs as often as you like.
