### ISSUE TITLE
JS error

### ISSUE THREAD

**Issue by stevesouders** [SpeedCurve-Metrics/SpeedCurve#125]
We're getting 100+ JS errors for Homeaway showing up in Jezr:

	Uncaught TypeError: Cannot read property '0' of undefined	HTML page	2668:31	/ha/platform-dashboard/test/160807_N8_b6a0d65554a914013773f28f4b...	Chrome 53	Mac OS X	hanoc@homeaway.com	64.245.52.2

Line 2668 is:
			  		thisFrame = data.frames[0].image.replace("http://wpt1", "https://wpt");

Can you fix? Probably need to check that data.frames exists and isn't null.

**Comment by zeman** [comment]
Added check to make sure first video frame exists before showing in scrubber.
