### ISSUE TITLE
CPU Usage charts are not shown anymore

### ISSUE THREAD

**Issue by zenderol** [SpeedCurve-Metrics/SpeedCurve#128]
**Browser:** Chrome
**Possible Reason:** WebPageTest result doesn't show the captured chrome dev-tools timeline
<img width="1182" alt="bildschirmfoto 2016-10-18 um 13 24 38" src="https://cloud.githubusercontent.com/assets/10632238/19475820/471693f6-9536-11e6-9b18-7b651048994b.png">

**Comment by zeman** [comment]
Please send a specific example to support@speedcurve.com so we can
investigate.

**Comment by zeman** [comment]
There was an issue in the WebPageTest agents with Chrome 54 and HTTP2. We've just pushed an agent update that should fix these issues and restore CPU data.
