### ISSUE TITLE
Tests API - returned location is always "US_West"

### ISSUE THREAD

**Issue by deenamo** [SpeedCurve-Metrics/SpeedCurve#13]
E.g. the following test run from Brazil:
https://speedcurve.com/test/150702_SJ_QZG/ 

Shows as US West in API:
https://api.speedcurve.com/v1/tests/150702_SJ_QZG
```
{
    ...
    "test": "150702_SJ_QZG",
    "location": "US_West",
    ...
}
```

**Comment by mistergaskill** [comment]
I'm also seeing this issue.

**Comment by zeman** [comment]
Fixed. This was a hangover from when SpeedCurve only tested from one location. Also added location to the urls method.

**Comment by mistergaskill** [comment]
Wow, I thought I was taking crazy pills when I saw the data in my logs change. Thanks for the quick update!

**Comment by deenamo** [comment]
Thanks for seconding this issue, Jeff :)
