### ISSUE TITLE
Deploy tab doesn't show image download size despite showing all other numbers

### ISSUE THREAD

**Issue by asuth** [SpeedCurve-Metrics/SpeedCurve#134]
![screen shot 2016-11-01 at 4 49 12 pm](https://cloud.githubusercontent.com/assets/46909/19911838/62966412-a053-11e6-9351-19c04e450550.png)

In this example, you show the total (2.4mb), and all the other metrics (which add to ~600kb), but don't show the images (~1.8mb)

**Comment by zeman** [comment]
Yikes, that's an oversight. Fixed now.
