### ISSUE TITLE
Don't use session state to record user naviagation

### ISSUE THREAD

**Issue by lukestephenson** [SpeedCurve-Metrics/SpeedCurve#135]
I'm trying to compare two different experiments in two chrome tabs.  I open tab one and select the correct site variant.  I then open tab two, and pick a different site variant.

In browser tab one, I now change from the speedcurve tab `site` to `responsive`.  Bug - Browser tab one has now changed and has the same variants as the second browser tab.

All state regarding the page being viewed should be communicated in the browser url.

**Comment by okor** [comment]
I've also experienced very frustrating experiences with this same scenario. I strongly advise moving all state into the URL, exclusively.

**Comment by zeman** [comment]
I believe we fixed this a few months ago. Please let me know if you still have any issues with mutiple tabs open.
