### ISSUE TITLE
Greater User Management

### ISSUE THREAD

**Issue by flatiron32** [SpeedCurve-Metrics/SpeedCurve#138]
SpeedCurve has taken off like wild fire and now more of my day is user management than I would like. Two things would make this easier.

1. Team level admin users, who ware able to add users to the team.
2. Sharable link to allow people to self serve join a team.

A big win would be SSO/SAML or AD integration.

**Comment by zeman** [comment]
Glad to hear it!

1. If you invite a user to a team and give them edit permissions then they can already invite other users to that team.
