### ISSUE TITLE
API exposed by LUX shim gets wiped out by LUX.js

### ISSUE THREAD

**Issue by cewhiting** [SpeedCurve-Metrics/SpeedCurve#139]
The lux shim file available here: https://speedcurve.com/features/lux/#snippet exposes an API with the following 4 entries:

`mark: function()`
` measure: function()`
`gaMarks: array`
`gaMeasures: array`

When the lux.js file is downloaded it re-defines the public API which wipes removes the previously available `gaMarks` and `gaMeasures` arrays.

The new API looks like this:
`mark: function()`
` measure: function()`
`init: function()`
`send: function()`
`addData: function()`
`doUpdate: function()`
`beaconUrl: String`
`samplerate: number`
`auto: boolean`
`label: String`,
`version: String`

The use case is as follows: "I would like to invoke LUX.mark(markName); so that LUX can record a performance mark but I would also like to be able to invoke LUX.getMark(markName); (or some equivalent) so that I can also log the mark using my own tools for additional verification/analysis."

If the Nav Timing API is supported by the browser I can simply invoke performance.getEntriesByType('mark') or by name so that I can log these values myself. If the Nav Timing API is not available I could get the performance mark that LUX recorded in `gaMarks`. But, since LUX.js removes `gaMarks` when it loads and there is no API function available to get a previously recorded mark when the Nav Timing API is unavailable I cannot support this use case.

The request is to add a function to both the LUX shim and LUX js file that replaces the `gaMarks` and `gaMeasures` arrays currently in the SHIM with a function getMark and getMeasure. Perhaps there could be a getEntries() function to return all entries like the Nav Timing API (this would replace gaMarks/gaMeasures and serve the current use case that LUX.js needs these 2 arrays for) and also a getEntriesByType/Name to serve our use case?

**Comment by stevesouders** [comment]
gaMarks and gaMeasures are not part of the [API](https://speedcurve.com/features/lux/#api). They're just helper variables for our internal code. We've intentionally not attempted to implement the entire User Timing spec - only the parts that are needed for LUX. The getEntries* functions would be too much work to replicate for public consumption.

**Comment by newdaniel** [comment]
Hi Steve, I noticed that http://caniuse.com/#feat=nav-timing says that globally 94.35% of browsers support the Nav Timing api with the main exceptions: Opera Mini (3.01%), Safari 8.1 (0.12%) and IE 8.0 (0.36%). When does it make sense to let go of the shim to support these browsers and use the native JS api? Our current modification of the lux shim designed to allow us to use a single function to capture the PageUsable mark for our own internal logging as well as to log it via LUX isn't capturing all the marks. I'm now wondering if we should keep debugging it, or just instead remove the portions of the shim that re-implement Nav Timing api for older browsers and thus allow us to fetch the value of our custom mark via performance.getEntriesByType('PageUsable') so we can log it to Omniture and other server side locations.

What do you think?

**Comment by stevesouders** [comment]
newdaniel: If by "shim" you're referring to lux.js, that is a replacement for User Timing (not Nav Timing as you mentioned). User Timing is still not support on mobile safari which is a significant and important amount of traffic, so we recommend continuing to use lux.js. However, if you prefer to use the native User Timing implementation, lux.js will still collect your metrics and report them as part of the LUX dashboards. In other words, you don't have to use LUX.mark() and LUX.measure() unless you want metrics from those browsers that don't support User Timing.

**Comment by newdaniel** [comment]
Ah, that makes more sense. Thanks for correcting me Steve. http://caniuse.com/#feat=user-timing is the one I should have been looking at. We'll definitively keep using LUX.mark() and LUX.measure().
