### ISSUE TITLE
Speedcurve dashboard mode

### ISSUE THREAD

**Issue by t-kelly** [SpeedCurve-Metrics/SpeedCurve#140]
![image](https://cloud.githubusercontent.com/assets/4837696/20567067/5e3e46b4-b165-11e6-839e-ff8ff49e6847.png)

Hey guys! Love the new 'Favorites' tab -- had the idea the other day of throwing it up on a dashboard TV in our office. Problem is that the styling isn't really optimized for a large displays/dashboard. 

It would be great if we create a dashboard mode that is optimized for large screens. Maybe hiding the navigation and filter sections? Decreasing the vertical height of the charts to allow more information to be displayed? Maybe this mode could be enabled via a URL parameter?

Let me know what you think!

**Comment by jleatherman** [comment]
Yes, I would love this as well, for the same reasons.

**Comment by zeman** [comment]
Are your dashboard TVs portrait or landscape?

**Comment by jleatherman** [comment]
Ours are landscape, but I would consider a portrait orientation if we could increase font sizes.

**Comment by t-kelly** [comment]
It would be great if this dashboard styling could be enabled via a URL parameter and that you could enable that parameter when creating a share link.

**Comment by zeman** [comment]
We're working on this at the moment and a bit more detail around how people interact with your TVs would be really helpful:

What resolution are your TVs running at? 1920x1080?
Roughly how far away are people when looking at them?
What particular elements do you want people to focus on? The median stats or the trend of the chart?
Do people walk up closer for more detail or just glance and then go to SpeedCurve in a browser to investigate?
How many charts do you feel should fit on the screen at once vs cycling through single charts?

Thanks!

**Comment by t-kelly** [comment]
> What resolution are your TVs running at? 1920x1080?

Yes, in both portrait and landscape orientations.

> Roughly how far away are people when looking at them?

Between 3-12 feet

> What particular elements do you want people to focus on? The median stats or the trend of the chart?

Hard to say, but I feel like trends?

> Do people walk up closer for more detail or just glance and then go to SpeedCurve in a browser to investigate?

Personally I use the dashboard as a monitoring dashboard to know if anything weird is going on. Typically investigate further on my desktop.

> How many charts do you feel should fit on the screen at once vs cycling through single charts?

Single charts could work for landscape orientation, but not as well for portrait. For reference, I'm currently loading 3 charts on our portrait orientated dashboard [using this proxy app](https://speedcurve-dashboard.herokuapp.com/) (⚠️slow to load). Datadog has pretty cool dashboard creator... but I could understand how that might fall out of the scope of this initiative.

**Comment by t-kelly** [comment]
Also, our dashboard setup can only access public URLs, so providing this feature through the share link would work really well for us 😄

**Comment by josephwynn-sc** [comment]
Hey folks! We've just added a `tv=1` query parameter that will hide a lot of the UI and reduce spacing to fit more on the page. The parameter will work on any dashboard URL including share links -- just pop `&tv=1` at the end of the URL.

Any feedback is appreciated. This is just a first pass - we can tweak font sizes, line widths, etc if that improves readability.
