### ISSUE TITLE
Visually Complete time for Firefox sometimes includes "Firefox asking to send data to Mozilla" visual change

### ISSUE THREAD

**Issue by mchipouras** [SpeedCurve-Metrics/SpeedCurve#141]
We’re seeing an occasional issue in Speedcurve where the visually complete time is affected by a setting in Firefox that asks about sending data to Mozilla. "Firefox automatically sends some data to Mozilla so that we can improve your experience"

The test https://wpt.speedcurve.com/video/compare.php?tests=161204_MK_4ef58e69db262105ad4512f756b704fd-r%3A3-c%3A0&thumbSize=200&ival=100&end=visual indicates that it is visually complete at 8.3 seconds, which is when the Firefox browser shows its question, but is not a change in our site’s appearance. You can see this behavior by clicking on the filmstrip images for 8.2 and 8.3 seconds and noting the difference. 

Can you change the Firefox configuration so it does not ask this question?

**Comment by zeman** [comment]
Thanks for reporting that. We've logged an issue with WebPageTest.

https://github.com/WPO-Foundation/webpagetest/issues/773

**Comment by zeman** [comment]
We've rolled out WebPageTest agent 341 which has a fix for this issue. Let us know if you continue to see the popup in Firefox.

**Comment by pbomb** [comment]
Great, thanks for the quick turnaround!

**Comment by mchipouras** [comment]
Awesome Thanks!
