### ISSUE TITLE
Be able to customise the colours of each Site

### ISSUE THREAD

**Issue by jpedroribeiro** [SpeedCurve-Metrics/SpeedCurve#144]
When you add a **Site**, it would be useful to have a colour picket widget so we can colour code how they look on the **Benchmark** graphs (and match their branding).

**Comment by josephwynn-sc** [comment]
Another argument for being able to specify a site colour is to maintain consistency across charts. What I mean is that currently the same colours are assigned incrementally so the first data series is always amber, the second is blue, the third is green, etc. This means that if you change the number of series in a chart, the colours change:

![screenshot from 2018-05-10 09-03-32](https://user-images.githubusercontent.com/31634862/39839679-099dc8c6-5431-11e8-9f10-f94593cbf294.png)

See how the blue series is not the same site in both charts? This can be confusing, especially when using these charts to report to non-technical stakeholders.

**Comment by zeman** [comment]
You can now choose a colour for a site in the settings.
