### ISSUE TITLE
Repeat View Testing

### ISSUE THREAD

**Issue by bteller** [SpeedCurve-Metrics/SpeedCurve#145]
I'm wondering if any consideration has been given to having performance reports around repeat visit timings. While optimizing for the first view (clean browser) is a good thing, making sure proper cache headers are set to further optimize the repeat view is something else we'd like to monitor. Is this a planned feature? I didn't see the capability in SpeedCurve today.

**Comment by zeman** [comment]
We are considering adding full support for repeat views. At the moment you can use a simple WebPageTest script to do a repeat view.

http://support.speedcurve.com/settings/add-a-repeat-view-using-a-wpt-script
