### ISSUE TITLE
Questions Related With the API

### ISSUE THREAD

**Issue by JoseDSolano** [SpeedCurve-Metrics/SpeedCurve#147]
Hi Support:
I have a few questions for you, 
We want to implement your API to generate some reports in our application.
We want to know if its possible to create, edit a test by requesting your API, or only we can get the information of the tests already made on the Web App. Also me want to know if is possible set the settings for a test using your API, if so could you please provide us more Documentation about how to do it.
Finally we want to know if is possible with a single URL create  3 test on different browsers.
If your API don't do any of these things, Do you think to implement them on a new version?

Thanks for your help

Jose Solano
dsolano@builderhomesite.com

**Comment by zeman** [comment]
Please send questions like this through to support@speedcurve.com
