### ISSUE TITLE
Add instructions re: preferred method for +1-ing an issue

### ISSUE THREAD

**Issue by MickeyKay** [SpeedCurve-Metrics/SpeedCurve#149]
I know that tracking "votes" in Github issues can be a challenging and inconsistent thing. As such, it'd be nice if the readme had some basic instructions for filing a new issue and/or adding a +1 vote to an existing one (e.g. do you prefer an new comment on the issue, or a simple 👍 reaction? Also might be worth considering an issue template.

**Comment by josephwynn-sc** [comment]
I realise I'm more than a little late but this is an awesome suggestion! I've updated the README to be a bit more helpful, and I've added an issue template.
