### ISSUE TITLE
root certs update + OCSP request included in waterfall

### ISSUE THREAD

**Issue by csabapalfi** [SpeedCurve-Metrics/SpeedCurve#151]
See example wpt here https://wpt.speedcurve.com/details.php?test=170428_G3_0d48efb90b27635515757918d5072843&run=1#waterfall_view_step1

This seems especially weird since we have OCSP stapling configured.

Is it possible that refreshing the root certs update triggers the OCSP request?

I understand that this is not a problem with SpeedCurve but WebPageTest/Chrome but it'd be great to get some assistance in this :)

**Comment by zeman** [comment]
We've checked in with Pat from WebPageTest and he believes the requests are being triggered by your SSL certs. For the requests to show up in the waterfall they must be coming through the browser process. The requests are to do with the [root certs in Windows.](https://support.microsoft.com/en-us/help/2677070/)

Pat has now pushed a new version of the WebPageTest agent that specifically blocks and removes any requests to "ctldl.windowsupdate.com" and we've rolled it out on SpeedCurve.

Please let us know if you see any requests like this again going forward.

**Comment by csabapalfi** [comment]
Nice one! Thanks! 👍

Will try to look into our certs next week.

**Comment by csabapalfi** [comment]
Looks like we still have this issue. The root cert update happens and I see an OCSP request for a CA's cert that affects our TTFB.

<img width="406" alt="screen shot 2018-07-20 at 00 53 28" src="https://user-images.githubusercontent.com/181959/42988042-1a790a44-8bf3-11e8-8e24-968ec065b006.png">

**Comment by csabapalfi** [comment]
SpeedCurve WPT result: https://wpt1.speedcurve.com/details.php?test=180718_X4_b1a7a0cd6ef023efae3734411b654f46&run=3#waterfall_view_step1

WebpageTest result: https://www.webpagetest.org/result/180720_N3_a9a81f677f6bd16086005ce1b55a0036/1/details/#waterfall_view_step1

This is still a WPT issue it seems and not something about SpeedCurve but definitely affects our results.

**Comment by zeman** [comment]
Hmmm... these tests are running on Linux so nothing to do with Windows root certs. Since this is a WPT issue I'd suggest logging an issue in the [agent project.](https://github.com/WPO-Foundation/wptagent/issues)

**Comment by josephwynn-sc** [comment]
FYI: www.homeaway.com has an extended validation certificate, so Chrome will make an OCSP check regardless of whether stapling is enabled.
