### ISSUE TITLE
Feature request: aggregate vs individual view

### ISSUE THREAD

**Issue by MickeyKay** [SpeedCurve-Metrics/SpeedCurve#152]
Loving SpeedCurve! Thanks for a great product.

One request re: the "Favorites" view, which might be applicable outside of that view as well. . .

At present, one has the ability to specify individual URL Labels to include in a "favorites" chart. If no specific URL labels are explicitly specified for inclusion, then all URL's are included and a single aggregate value is shown. If, however, individual URL labels are manually selected for inclusion, then the resulting chart/metrics are individuated (e.g. one chart line, and numeric metric, per URL label). This is certainly useful, however would like to be able to find the aggregate averages of a specific subset of URL labels. For example, as a team we have URLs spread across different technologies (e.g. React vs WordPress). I would like to get averages for both app types, however getting the cumulative average across both is like mixing apples and oranges. Thus, at present, getting aggregate numbers across just the React subset, for example, requires manually averaging all of the individual URL metrics that are output. 

So the feature I would love to see is a simple toggle that enables/disables aggregate vs individual URL label view. Thanks!

**Comment by zeman** [comment]
Having multiple labels would resolve this. #116 should fix this.

**Comment by timmfin** [comment]
Thank you!
Spark by Readdle
