### ISSUE TITLE
Budget to send alerts when over the limit only

### ISSUE THREAD

**Issue by jpedroribeiro** [SpeedCurve-Metrics/SpeedCurve#154]
Hi,

We'd like to put forward a suggestion for an improvement to budget alerts. For our use case we are only really interested in getting alerts when a metric goes over our budget and less concerned when they fall under.

For example, we like to keep our backend response time on 3G at 1.8s. Occasionally this will fall to 1.7s, but we aren't concerned about that. We are concerned however when it goes >= 1.9s

It would be great when ticking the box for receiving email/webhook alerts if there was select list or radio buttons with the following options:
Send when over threshold
Send when under threshold
Send when either under or over threshold
At present we have to set our threshold higher than we would like to avoid alerts constantly flapping between tests.

**Comment by zeman** [comment]
Sorry, no plans to introduce these options.
