### ISSUE TITLE
Short Note text is truncated at edge of chart

### ISSUE THREAD

**Issue by jleatherman** [SpeedCurve-Metrics/SpeedCurve#156]
If a note is added to a test which is at the beginning of the chart. Notes for tests near the end of the chart correctly justify.

![2017-06-09 14_18_52-site _ speedcurve](https://user-images.githubusercontent.com/12204030/26994953-082d9bde-4d1f-11e7-9207-c563cd20d49b.jpg)

**Comment by zeman** [comment]
It's a tricky edge case to flip the label alignment. Not ideal but if the whole label needs to be seen the date range can be expanded or notes turned off.
