### ISSUE TITLE
Round numbers

### ISSUE THREAD

**Issue by timuric** [SpeedCurve-Metrics/SpeedCurve#159]
From time to time I see such funky floats in the dashboard

![image](https://user-images.githubusercontent.com/4006792/27627841-73ce57fc-5bed-11e7-8dc9-cebc8ea4ad3f.png)

**Comment by zeman** [comment]
Can you please send the URL for a dashboard where you're seeing this to support@speedcurve.com

**Comment by zeman** [comment]
Fixed.
