### ISSUE TITLE
Mising requests and weird timing in FF

### ISSUE THREAD

**Issue by lsuchanek** [SpeedCurve-Metrics/SpeedCurve#16]
There are missing request and weird timing in tests from Firefox.

https://www.dropbox.com/s/smxza0l6czxhfok/Screenshot%202015-07-20%2017.07.51.png?dl=0

**Comment by zeman** [comment]
Hi,

This looks like an issue with a specific account or url. Can you please email support@speedcurve.com with your account login email address and a link to the specific firefox test where you are seeing issues.

Pat from WebPageTest has been making a number of improvements to the Firefox agents and we've recently upgraded to the latest version of WebPageTest. Are you still still seeing the same data issues on the most recent tests?

Cheers,
Mark
