### ISSUE TITLE
Time to Interactive (TTI) in Speedcurve

### ISSUE THREAD

**Issue by t-kelly** [SpeedCurve-Metrics/SpeedCurve#161]
![Alt text](https://monosnap.com/file/LRyvqR8F8IEm4yxhf8Jux4BzXk31CP.png)

WebPageTest has recently added [Time to Interactive](https://github.com/WPO-Foundation/webpagetest/blob/master/docs/Metrics/TimeToInteractive.md) to their test results. It would be great if you could access this metric inside Speedcurve!

**Comment by tammyeverts** [comment]
Thanks for your feedback, Thomas! We've talked about this a fair bit and have decided to hold off on it. Because this metric is still in beta on WPT, we're cautious about adding it to SpeedCurve. For now, we think custom metrics are still a much more reliable indicator of user experience.
