### ISSUE TITLE
Get empty response when using SpeedCurve API

### ISSUE THREAD

**Issue by alexr1978** [SpeedCurve-Metrics/SpeedCurve#162]
When I create requests https://api.speedcurve.com/v1/urls/71796
https://api.speedcurve.com/v1/urls/71797
I usually get response with empty data.
For example
{"url_id":71796,"url":"http:\/\/cdn.playbuzz.com\/content\/Automation\/production_story_embed.html","label":"","tests":[]}

**Comment by zeman** [comment]
Not tests have been run for these URLs yet, which is why you're not seeing any data via the API. Click "Test Now" in the SpeedCurve UI or wait for your scheduled tests and then you'll get data via the API.
