### ISSUE TITLE
Timeline rendering

### ISSUE THREAD

**Issue by timuric** [SpeedCurve-Metrics/SpeedCurve#163]
Not sure if this is a bug or rather a usability issue, but timeline charts have weird looking artifacts which make them less readable.

I would also argue that leaving out smoothing and quantizing time intervals would make charts more consumable. 

![image](https://user-images.githubusercontent.com/4006792/28465770-45914f94-6e2a-11e7-8da3-c4edf8cdb159.png)

**Comment by tammyeverts** [comment]
Thanks for your feedback. Spikes on the chart are due to variability (e.g., network related) in tests. We don't want to hide that variability by smoothing out results.
