### ISSUE TITLE
Need ability to have a title on a favorites page

### ISSUE THREAD

**Issue by jleatherman** [SpeedCurve-Metrics/SpeedCurve#164]
Currently, there is no way to show a custom title on a favorites page. 

This makes it very unwieldy for the purposes of a dashboard with multiple projects.

![image](https://user-images.githubusercontent.com/12204030/28695078-e7a7aa9c-72e1-11e7-9c18-31ba89fb3e35.png)

**Comment by zeman** [comment]
We're working on adding multiple Favourites dashboards per team and each one will have it's own title.

**Comment by stevesouders** [comment]
Multiple favorites solves this
