### ISSUE TITLE
Add option for consecutive checks for alerts

### ISSUE THREAD

**Issue by MickeyKay** [SpeedCurve-Metrics/SpeedCurve#167]
Alerts are great, however because they only seem to alert on changes between 2 subsequent checks, they can be really noisy. For example, we test twice per day and the AM timings are always different from the PM timings. Right now, this causes alerts to fire pretty much on every check. I would like the option to specify that alerts should be scoped to 2+ consecutive checks, much like (for example) Sumo Logic offers with the `consecutive` flag on their outlier checks: https://help.sumologic.com/Search/Search-Query-Language/Search-Operators/outlier

Thanks!

**Comment by josephwynn-sc** [comment]
We've just started rolling out a new [performance budgets system based around **Favorites charts**](http://support.speedcurve.com/synthetic-settings/performance-budgets) that supports this feature. It's referred to in the UI as "Only alert when the budget is crossed \<X\> times"
