### ISSUE TITLE
Not all tests are shown when only viewing 1 width in the responsive dashboard

### ISSUE THREAD

**Issue by ronaldlokers** [SpeedCurve-Metrics/SpeedCurve#17]
You get less test results in the graphs when you select only 1 width in the responsive dashboard.

Left: Show all widths
Right: Only show 320px

![fullscreen_23_07_15_15_42](https://cloud.githubusercontent.com/assets/303084/8851784/db423fc0-3151-11e5-9b01-9be33add3898.png)

**Comment by zeman** [comment]
Hi,

This looks like an account or url specific issue. Can you please email support@speedcurve.com with the issue and your account login email address so we can investigate.

Cheers,
Mark
