### ISSUE TITLE
Cannot register for free trial

### ISSUE THREAD

**Issue by danpalmer** [SpeedCurve-Metrics/SpeedCurve#172]
Steps to reproduce:

1. Click "Free Trial" in the top right of the navigation on https://speedcurve.com/
2. Enter first name, last name, valid email, and secure password.
3. Click "Next step".

What I expect to happen:
I'm taken to the "next step" of registration.

What actually happens:
I'm taken back to the home page at https://speedcurve.com/ with no error message, no indication that anything went wrong.

**Comment by danpalmer** [comment]
It appears that a workaround is to use a less secure password.

**Comment by josephwynn-sc** [comment]
Hi @danpalmer! I was unable to reproduce this - could you provide some extra information?

- When you signed up successfully, was it with the same email as when it failed?
- What software (and settings) do you use to generate a secure password?
- Do you have an example password that has the same characteristics as the one that failed?

Thanks!
