### ISSUE TITLE
Feature request: "God View"

### ISSUE THREAD

**Issue by MickeyKay** [SpeedCurve-Metrics/SpeedCurve#173]
We have numerous teams using SpeedCurve within our organization, and for super-admins it would be useful to have a "God View" in which _all_ team data can be compared. This gets tricky given the apples-vs-oranges nature of different test/page types, however this could be solved in a few different ways:
- make "labels" a proper taxonomy that is shared across an entire org to ensure all teams use consistent labelling
- enable filtering in this "God View" to allow for segmenting by teams, labels (aka templates), devices, etc. Basically this would be a master Site view with all of the same filters that currently exist, but displaying data across all teams as opposed to just one

cc @franjohn21 @parshap

**Comment by zeman** [comment]
I don't think we'll add another level of UI like this any time soon and as you pointed out there are challenges with comparing data across teams if the settings are not consistent.

We have seen organizations solve this in different ways.

1. **Add a new team to benchmark across sites.** Our vision for a "team" is that it represents a website in its production, staging and dev states along with a bunch of competitors. If an organization wants to compare a whole lot of its own websites then put those all in a new "Benchmarking" or "Exec Summary" team. This also ensures the settings are consistent across all the sites tested.

2. **Use the API to pull out specific data**.  Often large orgs with lots of different sites and teams already have their own reporting tools internally to compare data and business metrics across sites. We have a number of customers using the API to pull out the specific data they want and then visualizing them in their own tools.

@MickeyKay looks like you have plenty of checks budget left in your account to try out approach 1. and see if that add the view you're after.
