### ISSUE TITLE
Unhelpful labels on performance budgets

### ISSUE THREAD

**Issue by josebolos** [SpeedCurve-Metrics/SpeedCurve#174]
When a team has different performance budgets set up for different sites, regions or browsers that use the same metric (for example, SpeedIndex) there's no way to differentiate between them in the Settings screen ( `https://speedcurve.com/$ORG/$TEAM/settings/` )

![screen shot 2017-10-30 at 10 18 01](https://user-images.githubusercontent.com/1792637/32165781-d52cba6e-bd5b-11e7-9f52-b54942ad4617.png)

I was wondering if there's any way that the labels could be more helpful, maybe by allowing the text in them to be edited.

Likewise, in the "All budgets" screen ( `https://speedcurve.com/$ORG/$TEAM/settings/allbudgets/` ) there's only "Metric" and "URL label". On a site with two different budgets for Desktop and Mobile browsers, there's no way to differentiate them (except for the value):

![screen shot 2017-10-30 at 10 17 22](https://user-images.githubusercontent.com/1792637/32165783-d828efda-bd5b-11e7-8932-79396d97284b.png)

It would be cool if the region or browsers that the budgets apply to could be also displayed on the table.

**Comment by josephwynn-sc** [comment]
We've added two new columns to the "All budgets" page: **Browser** and **Region**. Hopefully that helps to disambiguate the budgets!

**Comment by josebolos** [comment]
Wow, that was quick! So happy! Thanks a lot for sorting this out!
