### ISSUE TITLE
Expose in-depth test information in /v1/tests/{test_id} API endpoint

### ISSUE THREAD

**Issue by josephwynn-sc** [SpeedCurve-Metrics/SpeedCurve#176]
Exposing more test information in the API would enable people to build their own dashboards that track metrics which aren't currently included in the API, like DNS times.

It might be useful to send a `requests` array, [like WebPagetest does](https://www.webpagetest.org/jsonResult.php?test=170925_F2_5d5240af5893dc08de057083f986260a).

**Comment by zeman** [comment]
Already available via the har file.
