### ISSUE TITLE
Notes are difficult to read when there are a lot

### ISSUE THREAD

**Issue by josephwynn-sc** [SpeedCurve-Metrics/SpeedCurve#177]
When there are lots of notes close together, it can be hard to tell which note goes with which vertical line. Having some hover styles might help to make it clearer?

![screenshot from 2017-11-21 14-38-47](https://user-images.githubusercontent.com/31634862/33050412-b40d4aae-cec9-11e7-9c0a-0eb66fa9a6c6.png)

**Comment by zeman** [comment]
There's now a hover style on the line which makes the relationship with the label clearer.
