### ISSUE TITLE
"Threshold" label shows seconds regardless of the metric

### ISSUE THREAD

**Issue by josebolos** [SpeedCurve-Metrics/SpeedCurve#178]
Very minor issue!

In the budget screen ( e.g. `https://speedcurve.com/$ORG/$TEAM/settings/budget/$BUDGET_ID/` ) the "Threshold" label shows "(Seconds)" as the unit, regardless of the metric being selected. This can be slightly confusing for people not familiar with budgets or the tool itself.

![screen shot 2017-11-23 at 10 27 13](https://user-images.githubusercontent.com/1792637/33168602-67bb77ae-d039-11e7-9b23-05194331d9e9.png)

**Comment by zeman** [comment]
Unable to recreate. Can you please tell us which browser you're using and if there are any JS errors in console.

**Comment by josebolos** [comment]
Hi Mark,

I'm experiencing the same results for Chrome and Firefox in macOS and Chrome in Linux.

This seems to be happening when editing an existing budget. I've managed to replicate it from scratch.

1. Create/edit a budget. Set the metric to "Total size".
2. Label shows "Threshold (KB)" as expected.

![screen shot 2017-11-24 at 10 30 32](https://user-images.githubusercontent.com/1792637/33206564-8ce3152c-d102-11e7-81fd-a0d8532017b0.png)

3. Save the budget.
4. Click to edit it. Label still shows "Threshold (KB)".
5. Change metric to "Total requests" (which don't have a unit).

![screen shot 2017-11-24 at 10 31 50](https://user-images.githubusercontent.com/1792637/33206615-b5b4646a-d102-11e7-8e2b-4ec6f6b1809b.png)

6. Save the budget.
7. Click to edit it. Budget now shows "Threshold (Seconds)".

![screen shot 2017-11-24 at 10 32 25](https://user-images.githubusercontent.com/1792637/33206653-d5e8b7a4-d102-11e7-914f-e43ecf25315b.png)

I'm wondering if maybe it only happens with "Total requests" because they don't have a unit?

No messages are shown in the console.

**Comment by zeman** [comment]
Got it. The default wasn't set correctly for request budgets. Thanks heaps for the detailed bug report!
