### ISSUE TITLE
Make rows in "All budgets" view a link

### ISSUE THREAD

**Issue by josebolos** [SpeedCurve-Metrics/SpeedCurve#182]
On the "All budgets" page (e.g. https://speedcurve.com/$ORG/$TEAM/site/ ) each budget listed is a row on a table that is make clickable with some clever javascript wizardry. This means that, for example, right clicking on the row won't get you an "Open in another tab" item. 

![screen shot 2018-01-10 at 17 18 34](https://user-images.githubusercontent.com/1792637/34786087-f2c28dd0-f62a-11e7-86ef-5dbe14950131.png)

If I have a dozen budgets on a site and I'm modifying them I would like to be able to open one of them without losing the whole list. For example, as shown in the picture, if I have an alert set up for a Samsung S4 I may want to see its value while setting up the limit for Chrome.

It would be cool is some or part of the row displaying the budget (at least the name!) could be a link so things link right clicking work as expected.

**Comment by josephwynn-sc** [comment]
Agreed that regular ol' `<a href>` would be better. While this is a fairly quick change, to maintain consistency across our UI we want to update all of our tables at once. I'll update this ticket once we've slotted this in to be done.

**Comment by josephwynn-sc** [comment]
We're reviewing our public issues as a team and have decided to close this ticket. These budgets are deprecated in favour of [Favorites Performance Budgets](https://support.speedcurve.com/get-the-most-out-of-speedcurve/create-performance-budgets-and-set-alerts).
