### ISSUE TITLE
Export LUX data

### ISSUE THREAD

**Issue by stevesouders** [SpeedCurve-Metrics/SpeedCurve#185]
There's an API to export synthetic data. We need a way to export LUX data. I propose we provide a way to export the raw data to S3 and GCloud. Rather than an API, this would be in Settings with the necessary credentials. Would customers still want an API to do this?

**Comment by sharathgowda1** [comment]
This feature would be great, we do a lot of operational data analysis and visualization outside of speedcurve.  It would be nice to get a dump of LUX data so that we can correlate with other metrics.

**Comment by colinbendell** [comment]
an export would likely be more efficient than an api call. would you dump as a parquet / orc or just a csv file? would it include resource timing as well or just navtiming?

**Comment by stevesouders** [comment]
This is now available as "beta". Please contact support@speedcurve.com to kick the tires.
