### ISSUE TITLE
Custom user agent string incorrectly appended 

### ISSUE THREAD

**Issue by technopagan** [SpeedCurve-Metrics/SpeedCurve#186]
Hi!

We're using the WPT Script section to define various custom commands for our test agents. Here's an anonymized example:

```
setUserAgent	foobar lorem ipsum
exec	console.log(window.foobar)
setHeader	X-Foo-Bar-Lorem: 1
navigate	https://www.example.com/?someparameter=1&otherparameter=12345
```

We rely on the setUserAgent string to be 100% correct so that we can bypass our bot captcha. Recently, our metrics started jumoing all over the place and I've noticed that we kept running into our bot captcha despite having configured the user agent as shown above.

So I've looked at which user agent string the SpeedCurve WebPagetest agents report back to me and I've found out that the user agent is now appended by SpeedCurve namings: 

`user-agent: foobar lorem ispum PTST/SpeedCurve/402`

This appended "PTST/SpeedCurve/402" is probably what is tripping our bot detection. This is unexpected behaviour since we defined a custom user agent without any hint at it being appended by other strings coming from SpeedCurve. 

Please advise on how we can get a clean user agent string back so that our measurements stop being meaningless. Thank you!

**Comment by zeman** [comment]
Hi Tobias,

You can control if the "PTST" and agent version number should be added to the UA string with the script command `speedcurve_removePTST	1` which replicates one of the WPT UI options.

More background here: http://support.speedcurve.com/synthetic-settings/adding-webpagetest-scripts-to-urls

Cheers,
Mark
