### ISSUE TITLE
Feature Request: Option to plot rolling averages on charts

### ISSUE THREAD

**Issue by hansede** [SpeedCurve-Metrics/SpeedCurve#188]
I would like to be able to plot rolling averages on charts and use them to trigger alerts. Preferably, I would be able to customize the number of prior data points that go into the rolling average, and optionally be able to put more weight on the more recent data points.

**Comment by josephwynn-sc** [comment]
We're reviewing our public issues as a team and have decided to close this ticket. You can now plot a linear regression trend line on all of your charts. It's not quite the same as a rolling average, but does help smooth out the lines.
