### ISSUE TITLE
Feature Request: Option to plot standard deviation on charts

### ISSUE THREAD

**Issue by hansede** [SpeedCurve-Metrics/SpeedCurve#189]
I would like to have the option of plotting standard deviations as a semi-transparent area on a chart. Potentially, it could be a rolling standard deviation on which I could trigger alerts.

**Comment by josephwynn-sc** [comment]
We're reviewing our public issues as a team and have decided to close this ticket. We don't see much of a use case for this, although we're willing to reconsider if there are some concrete examples and/or more demand for this feature.
