### ISSUE TITLE
Benchmark ranking incorrect

### ISSUE THREAD

**Issue by stevesouders** [SpeedCurve-Metrics/SpeedCurve#19]
Sometimes the ranking (#1, #2, #3) in the Benchmark dashboard doesn't match the actual metric values. See the attached dashboard.

![image](https://cloud.githubusercontent.com/assets/2819380/9251036/065cff8a-4186-11e5-9e2c-95eb7355410e.png)

**Comment by zeman** [comment]
Fixed.
