### ISSUE TITLE
Make performance budgets available through the API

### ISSUE THREAD

**Issue by josebolos** [SpeedCurve-Metrics/SpeedCurve#190]
I'm the performance engineer that has to keep an eye on the performance (and alerts) of 10+ different teams so I thought about creating a dashboard that lists all the currently defined performance budgets for all the teams and their status (over/under budget) so I can easily see how are we doing globally.

I've realised that there seem to be no details related to the performance budgets available through your API:
https://api.speedcurve.com/#speedcurve-v1-api

Is this correct? Would it be possible to add this to your API, please?

**Comment by zeman** [comment]
Thanks for the feedback, we do plan to add the performance budgets to the API.

Have you seen the new Status dashboard we added this week? It gives you an overview of the state of all perf budgets in a team. It should help provide the overview you are looking for. 

We're keen for feedback on what else you'd like to see? For example we were thinking of adding some trend lines. Would you find those useful or noisy?

<img width="1145" alt="screen shot 2018-06-08 at 9 47 19 am" src="https://user-images.githubusercontent.com/204268/41128025-f793cf36-6b00-11e8-8241-281d192045a5.png">

**Comment by josebolos** [comment]
Hi Mark! Glad to know that budgets will make it to the API.

The new status dashboard is indeed helpful for me, thanks for letting me know.

Regarding the trend lines, after asking about it to two of my teammates:
* One of us finds them helpful.
* One of us (me) finds the dashboard without the trend lines cleaner and easier to understand, specially when there are lots of budgets set up.
* One of us is undecided about them.

Sorry we can't be of any more help! 😃

**Comment by zeman** [comment]
We've now added performance budgets to the API.
https://api.speedcurve.com/#performance-budgets
