### ISSUE TITLE
API key with access to all the teams data

### ISSUE THREAD

**Issue by josebolos** [SpeedCurve-Metrics/SpeedCurve#191]
Sometimes it would be useful to be able to use the API to gather information across the whole organisation so it can be used to show how are we doing as a whole. See #190 for an example of this (potential) usage.

If my understanding is correct, each team has currently a separate API key, which makes this process a bit cumbersome, as retrieving data from for example 10 different teams each team requires managing 10 different API keys.

Would it be possible to add an API key with "admin" permissions, that could access data from all the teams? If necessary I think it could even be made read-only, so there's no risk of, for example, triggering accidental tests across the whole org, in case of a misconfiguration or code error.

**Comment by zeman** [comment]
We've reviewed this as a team and decided not to implement this. Having an API key per team is a security feature and we'd recommend managing your API's for each team in a programmatic way.
