### ISSUE TITLE
Performance Budget Status broken

### ISSUE THREAD

**Issue by zenderol** [SpeedCurve-Metrics/SpeedCurve#192]
### Issue type
  - [ x] Bug report

### Current behaviour

When opening the Performance Budget status board (https://speedcurve.com/beta-welt/status/), the dashboard is not displayed. I can see the following error in the console:
![grafik](https://user-images.githubusercontent.com/10632238/41769510-cd8c5504-760f-11e8-82d8-77ad07f71d31.png).
This happened after adding a new User Timing to our Favourites Board from which the Performance Status Board is created.

### Expected behaviour

Visible dashboard.

**Comment by zeman** [comment]
@josephwynn-sc there are a few errors in Raygun for this one.

**Comment by josephwynn-sc** [comment]
Thanks for reporting this! There was an edge case that we weren't accounting for, which is when you set a budget on a custom metric and later delete the metric. This should be fixed now :)
