### ISSUE TITLE
Missing space in description of Benchmarking on /admin/teams/add/

### ISSUE THREAD

**Issue by jleatherman** [SpeedCurve-Metrics/SpeedCurve#193]
### Issue type

  - [ ] Feature request
  - [X] Bug report
  - [ ] Question (please email questions to support@speedcurve.com)

### Current behaviour

Missing space in description of Benchmarking.
`Which industry or category does your website belongto?`

### Expected behaviour

Should be `belong to`.

**Comment by josephwynn-sc** [comment]
Thank you for reporting this! Fixed :tada:

**Comment by stevesouders** [comment]
There are very few people more obsessed with typos than me, but I think you might be one of them James!

**Comment by jleatherman** [comment]
It borders on dysfunction, actually. :/
