### ISSUE TITLE
Synthetic script content gets mangled on second save

### ISSUE THREAD

**Issue by sergeychernyshev** [SpeedCurve-Metrics/SpeedCurve#195]
### Issue type

  - [ ] Feature request
  - [x] Bug report
  - [ ] Question (please email questions to support@speedcurve.com)

### Current behaviour

When I submit a script with what looks like an HTML entity, they get converted into entities next time they are displayed. As a result, scripts are mangled when saved second time (first time works fine).

In particular a cookie value having `foo=bar&timestamp=blah` in it gets converted into `foo=bar×tamp=blah` after I save the form second time (after making a different change, like adding another URL, for example).

### Expected behaviour

Scripts should stay as they were entered after I update site settings as many times as I want.

### Any other useful information

See screenshots
![original script](https://user-images.githubusercontent.com/38076/43481304-959991f6-94d3-11e8-8ab5-01c4714b0704.png)

![after form is submitted](https://user-images.githubusercontent.com/38076/43481292-8cddf890-94d3-11e8-8e07-da7d2aa958e2.png)

**Comment by josephwynn-sc** [comment]
Sorry for the delay on this, Sergey! It should be fixed now :)
