### ISSUE TITLE
Support %url% in scripts

### ISSUE THREAD

**Issue by sergeychernyshev** [SpeedCurve-Metrics/SpeedCurve#198]
### Issue type

  - [ ] Feature request
  - [x] Bug report
  - [ ] Question (please email questions to support@speedcurve.com)

### Current behaviour

SpeedCurve doesn't let scripts to have `%url%` as a parameter to `navigate` command while WebPageTest supports it.

Following message is displayed when script text area loses focus `Script must include a "navigate" command followed by a tab and url.`

### Expected behaviour

Tests should run using the URL provided in the URL field which is supported by WebPageTest.

### Any other useful information

This helps a lot with script re-use and to avoid mistakes with copy/pasting URL twice, once in the field and once in the script.

**Comment by zeman** [comment]
Good spotting! Fixed.
