### ISSUE TITLE
Don't show 0 values in the graph

### ISSUE THREAD

**Issue by ronaldlokers** [SpeedCurve-Metrics/SpeedCurve#20]
I cannot see the amount if images in the page becuase right on top of it there is a value of 0 for "other sizes". Because of this I always get the "other sizes" value instead of the number of images when I hover the dot.

![fullscreen_17_08_15_10_40](https://cloud.githubusercontent.com/assets/303084/9301199/fe2c6bbc-44cc-11e5-99cb-eb922cd675b0.png)

**Comment by kennydee** [comment]
:+1:

**Comment by zeman** [comment]
We've rolled out a fix to slightly offset content types with 0 values so you can now select the one you're after. Also enabled hover for the content type area so you don't have to hover over the dot.

Let me know if you still have any interaction problems.
