### ISSUE TITLE
Make LUX 95th Percentile configurable

### ISSUE THREAD

**Issue by shawno** [SpeedCurve-Metrics/SpeedCurve#200]
### Issue type

  - [x] Feature request
  - [ ] Bug report
  - [ ] Question (please email questions to support@speedcurve.com)

### Current behaviour

A client's team has established RUM targets with their previous tool at the 90th percentile, instead of 95th. This seems like something that could be parameterized and made configurable for each account.

### Expected behaviour

Somewhere in the LUX settings, allow me to specify an interger between 1 and 100 to be used as the "Nth percentile" for the "Stat" value in LUX reports.

![Screen Shot 2019-04-11 at 4 11 36 PM](https://user-images.githubusercontent.com/1256782/55998760-8347e700-5c74-11e9-80cb-0ebf841aae31.jpg)

**Comment by zeman** [comment]
Thanks, we've now added 90th percentile as another Stat option.

**Comment by shawno** [comment]
👍
