### ISSUE TITLE
More POST APIs?

### ISSUE THREAD

**Issue by steveshulmanlaniel-toast** [SpeedCurve-Metrics/SpeedCurve#201]
### Issue type

  - [x] Feature request
  - [ ] Bug report
  - [ ] Question (please email questions to support@speedcurve.com)

### Current behaviour

As mentioned on the [API docs](https://api.speedcurve.com/#speedcurve-v1-api), 
> Version "v1" of the API is mainly read (GET) only, allowing you to pull results out for your own dashboards and analysis.

### Expected behaviour

Short version: I'd like to be able to create SpeedCurve objects via API. So I'd like more POSTs.

Longer form: we have a performance team, which has a coordination role across development teams here. We'd like individual teams to be able to stick their desired tests in a well-known location (e.g., `github.com/[org name]/[repo name]/speedcurve/tests.yaml`); we'd then use the Github APIs to find all such files, compare the existing body of SpeedCurve tests to the desired set, add any new desired tests to our SpeedCurve config via API, and run those tests.

For this to work, we need to be able to create tests programmatically. And for that we need `POST` rather than just `GET`.

Is there some other way to create SpeedCurve tests programmatically?

**Comment by zeman** [comment]
While mainly GET we do have a /settings endpoint where you can upload new tests and settings.

https://api.speedcurve.com/#settings

**Comment by josephwynn-sc** [comment]
We also have some new (undocumented) endpoints for managing URLs:

* Create a new URL in a site: `POST /v1/urls?site_id=$SITE_ID&url=$URL&label=$LABEL`
* Update an existing URL: `PATCH /v1/urls/$URL_ID`

Docs for these endpoints will be available soon.

**Comment by steveshulmanlaniel-toast** [comment]
This is awesome; thanks!

While I've got you on the blower: why does the /import endpoint accept new JSON as a query string (a potentially _very long_ query string) rather than as part of the POST body?

**Comment by josephwynn-sc** [comment]
@steveshulmanlaniel-toast I believe all of the POST endpoints accept either a query parameter _or_ POST body. I just noticed the docs refer to POST parameters as "query parameters" though, so I'll make a note to change that.

**Comment by steveshulmanlaniel-toast** [comment]
When I tried to submit a changed JSON document as a POST body, I got back a 400 error; when I submitted it as an URL-encoded query string, it succeeded. It's possible that I made some other mistake, such that the problem wasn't with the POST body, but I'm pretty sure it was a body-versus-query-string thing. Could you confirm? The 400 error, IIRC, told me that it wanted a 'data' query-string argument; when I supplied that (with what had previously been the POST body), it succeeded.

Cheers,
Steve

**Comment by josephwynn-sc** [comment]
The POST endpoints take a request body that looks like an application/x-www-form-urlencoded content type. Using curl, this looks like

```
curl -X POST -u $SPEEDCURVE_API_KEY:x \
     --data 'mode=merge&data={}' \
     https://api.speedcurve.com/v1/import
```

Or even

```
curl -X POST -u $SPEEDCURVE_API_KEY:x \
     --data 'mode=merge' --data 'data={}' \
     https://api.speedcurve.com/v1/import
```
