### ISSUE TITLE
Allow 90th percentile in all charts

### ISSUE THREAD

**Issue by atopal** [SpeedCurve-Metrics/SpeedCurve#203]
### Issue type

  - [x] Feature request
  - [ ] Bug report
  - [ ] Question (please email questions to support@speedcurve.com)

### Current behaviour

In issue #200 you added 90th percentile for the LUX dashboard (speedcurve.com/name/lux-perf/), which is great, but it's not available in any of the other charts or dashboards where I can add charts. The only options are median, 95th percentile and average.

### Expected behaviour

Can you please add 90th percentile to all chart options? I'd like to define a budget based on the 90th percentile and alert the team based on that, but currently we only have median (covers only 50%) and 95th (too much variance in the slowest 5%). 90th percentile strikes a nice balance between too much variety and not enough coverage and is probably widely used in performance KPIs.

**Comment by zeman** [comment]
We've now standardised on the (75th and 95th) percentiles across our dashboards. We added 75th as that's what the Google team are moving to for all Crux and Web Vitals metrics.
