### ISSUE TITLE
PHP Source Code Leaked

### ISSUE THREAD

**Issue by djeraseit** [SpeedCurve-Metrics/SpeedCurve#207]
### Issue type

  - [x] Bug report

### Current behaviour

Visit https://cdn.speedcurve.com/js/lux.js?id=498848576. A <?php file is the start tag. This is not a script file.

### Expected behaviour

PHP should execute and generate a script file

### Any other useful information

Just noticed this today.

**Comment by zeman** [comment]
Fixed. Thanks!!!
