### ISSUE TITLE
cannot view chrome data

### ISSUE THREAD

**Issue by siddharthram** [SpeedCurve-Metrics/SpeedCurve#209]
### Issue type

  - [] Feature request
  - [ x] Bug report
  - [ ] Question (please email questions to support@speedcurve.com)

### Current behaviour

Ask for data from chrome on US east coast. Graphs show IE performance instead
### Expected behaviour

Show Chrome data

### Any other useful information

![Screen Shot 2020-04-13 at 9 36 12 AM](https://user-
images.githubusercontent.com/890057/79138984-5720e380-7d6a-11ea-87bf-8897dc4b9b11.png)

**Comment by josephwynn-sc** [comment]
Hi there! The "IE" in your screenshot is a custom note, which you can view in your settings. You can confirm which browser the data is from by clicking on any point in the chart and then clicking "View test".

![Screenshot from 2020-04-14 11-46-28](https://user-images.githubusercontent.com/31634862/79171293-c0c1f000-7e45-11ea-912d-965941645d33.png)

Then scroll to the bottom of the test results page to see which test profile and browser were used:

![Screenshot from 2020-04-14 11-48-02](https://user-images.githubusercontent.com/31634862/79171349-dc2cfb00-7e45-11ea-9120-18c39e2c07b6.png)

(Screenshots are from my account; yours might look different)
