### ISSUE TITLE
Toggle the "notes" in the graph

### ISSUE THREAD

**Issue by ronaldlokers** [SpeedCurve-Metrics/SpeedCurve#21]
We shoot in a note whenever we release, but since we release very often you get distracted by all data. I would like to be able to toggle the visibility of notes, so we can see the details of the graph without the notes on top of it.

![fullscreen_17_08_15_10_40](https://cloud.githubusercontent.com/assets/303084/9301228/3e151d64-44cd-11e5-8674-498772dd9f99.png)

**Comment by stevesouders** [comment]
Yes, we have other folks with this issue. One workaround is to zoom in (drag a region in the graph). But we're working on adding a "hide notes" display option.

**Comment by tivac** [comment]
This looks like it's fixed? I see a `Notes` link on graphs which toggles note behavior, at least.

**Comment by ronaldlokers** [comment]
@tivac You are right, there is a link added to toggle the notes. I will close this issue :+1:
