### ISSUE TITLE
Feauture Request: Form Authentication

### ISSUE THREAD

**Issue by zenderol** [SpeedCurve-Metrics/SpeedCurve#210]
### Issue type

  - [x] Feature request
  - [ ] Bug report
  - [ ] Question (please email questions to support@speedcurve.com)

### Current behaviour

No oAuth is supported, only basic auth.

### Expected behaviour

Support of login forms for speed checks of protected sites with sensitive data. For instance when testing sites which are accessed from Application Load Balancers on AWS (https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html) 

### Any other useful information

Calibre supoorts it by default without any extra charges: https://calibreapp.com/docs/get-started/authentication

**Comment by josephwynn-sc** [comment]
You can use [WebPageTest Scripting](https://support.speedcurve.com/en/articles/1543261-testing-pages-that-require-authentication) to authenticate via a login form. Give us a shout at support@speedcurve.com if you need a hand setting it up!
