### ISSUE TITLE
Bulk Test Deletion

### ISSUE THREAD

**Issue by crate-scarter** [SpeedCurve-Metrics/SpeedCurve#214]
### Issue type

  - [x] Feature request
  - [ ] Bug report
  - [ ] Question (please email questions to support@speedcurve.com)

### Current behaviour

Right now, in order to delete tests, it is somewhat of a tedious process.  I'm going through finding tests that are clearly invalid due to long running times like TTFB > 20 seconds which is simply a failed experience.  I have to click the individual test, delete it, then go back to the original page to see the update.

### Expected behaviour

I would like to have a feature that you can select a threshold to delete tests over a certain number, rather than having to delete each test individually.  It would be nice to run a selection that returns all tests over a certain metric number and then do a bulk delete of those tests.

### Any other useful information

If this is a bug, please let us know your operating system, browser, relevant browser extensions, etc.

**Comment by josephwynn-sc** [comment]
We'd normally recommend that you use the [SpeedCurve API](https://api.speedcurve.com/) for this kind of thing. You could either use the [/v1/urls endpoint](https://api.speedcurve.com/#get-all-urls) to get the latest tests for all of your URLs, or iterate over each URL and [fetch all tests for each URL](https://api.speedcurve.com/#get-all-tests-for-a-url). You can then use the [/v1/tests/{test_id} endpoint](https://api.speedcurve.com/#delete-a-test) to delete the tests that exceed your threshold.

**Comment by crate-scarter** [comment]
I did exactly that.  It ended up taking a decent amount of time because I
needed to download all tests for a url for the last year, then filter out
to only the tests with a TTFB over 10 seconds then to run through them to
delete.  It nearly crashed my application a few times but it worked well
enough.
