### ISSUE TITLE
Downloading resources from wrong host

### ISSUE THREAD

**Issue by pk16011990** [SpeedCurve-Metrics/SpeedCurve#215]
### Issue type

  - [ ] Feature request
  - [x] Bug report
  - [ ] Question (please email questions to support@speedcurve.com)

### Current behaviour

When tetsted page contains CSS file on different host (eg. CDN) then sources  in CSS linked without host file (eg. fonts) are downloaded from host of page, not from CSS file host.

**Example:**

Tested Page: `https://example.com`

Used css in page: `https://cdn.example.com/style.css`

style.css content:
```
@font-face {
    font-family : 'Roboto';
    src : local('Roboto'), local('Roboto-Regular'), url("/fonts/Roboto400.woff2") format('woff2');
}
```

Font is downloaded from `https://example.com/fonts/Roboto400.woff2`, not from `https://cdn.example.com/fonts/Roboto400.woff2`

### Expected behaviour

Sources without host should be downloaded from host of initiator (css file) like real browsers (eg. Chrome)

**Comment by josephwynn-sc** [comment]
Hi! SpeedCurve runs tests in real browsers. If you think this is a SpeedCurve issue, please provide the actual tested page rather than an example page. A link to a SpeedCurve test result would be useful too. You can send this info to support@speedcurve.com if you don't want it to be public.

**Comment by pk16011990** [comment]
Oh, yes, you're right, my fault. Speedcurve sends requests with method OPTIONS to this static content (I don't know why, but it does not matter) and my CDN does not cache this type of requests.

Thanks for your answer and I'm closing the issue.
