### ISSUE TITLE
Settings menu item not visible

### ISSUE THREAD

**Issue by madsgodvinjensen** [SpeedCurve-Metrics/SpeedCurve#217]
### Issue type

  - [ ] Feature request
  - [x] Bug report
  - [ ] Question (please email questions to support@speedcurve.com)

### Current behaviour

Hey. I wanted to report a bug but can't find a better place than this to do it. Hope you can send it to the right people :)

After the new "Vitals" menu item has showed up, getting to settings is not possible on my computer. I'm on a 15" macbook and with a full screen browser window with only the bookmarks toolbar open, the settings menu item is not there. Hiding the toolbar displays the settings menu item - well kind of. See attached screenshots.

### Expected behaviour

I would imagine that the navigation should scroll when there are too many items to be visible on the screen.

### Any other useful information

15" MacBook Pro

OSX Catalina
Firefox 82

**Image 1: With toolbar open**

<img width="1552" alt="Screenshot 2020-12-14 at 16 08 18" src="https://user-images.githubusercontent.com/3774438/102098304-52e02500-3e27-11eb-8aff-863472b5c24a.png">

**Image 1: With toolbar closed**

<img width="1552" alt="Screenshot 2020-12-14 at 16 08 24" src="https://user-images.githubusercontent.com/3774438/102098368-65f2f500-3e27-11eb-981b-f770cfad0735.png">

**Comment by zeman** [comment]
Thanks for reporting that! Should be sorted now.
