### ISSUE TITLE
Response 500 when try to delete a test via API

### ISSUE THREAD

**Issue by chucknorristoolbox** [SpeedCurve-Metrics/SpeedCurve#219]
### Issue type

  - [ ] Feature request
  - [x] Bug report
  - [ ] Question (please email questions to support@speedcurve.com)

### Current behaviour
all steps via API
* add an URL to a site
* create a deployment for this URL
* wait some minutes
* read deployment
* read all referenced tests
* try to delete all referenced tests => first delete call results a response 500.

**request**
`options = {
  "url": "https://api.speedcurve.com/v1/tests/210122_9Q_915f574bd56fe851bf763de1cd9eb94f",
  "auth": {
    "user": "*******",
    "password": "*****"
  },
  "method": "DELETE",
  "resolveWithFullResponse": true,
  "simple": false,
  "json": true
};
request(options)`

**response**
`
{
  "statusCode": 500,
  "body": {
    "message": "Undefined variable: delete",
    "exception": "ErrorException",
    "file": "/app/common/TestResult.inc",
    "line": 895,
    "trace": [
      {
        "file": "/app/common/TestResult.inc",
        "line": 895,
        "function": "handleError",
        "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
        "type": "->"
      },
      {
        "file": "/app/app/Http/Controllers/TestController.php",
        "line": 96,
        "function": "deleteTest",
        "class": "SpeedCurve\\TestResult",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
        "line": 54,
        "function": "destroy",
        "class": "App\\Http\\Controllers\\TestController",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
        "line": 45,
        "function": "callAction",
        "class": "Illuminate\\Routing\\Controller",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
        "line": 239,
        "function": "dispatch",
        "class": "Illuminate\\Routing\\ControllerDispatcher",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
        "line": 196,
        "function": "runController",
        "class": "Illuminate\\Routing\\Route",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
        "line": 685,
        "function": "run",
        "class": "Illuminate\\Routing\\Route",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
        "line": 128,
        "function": "Illuminate\\Routing\\{closure}",
        "class": "Illuminate\\Routing\\Router",
        "type": "->"
      },
      {
        "file": "/app/app/Http/Middleware/SentryContext.php",
        "line": 28,
        "function": "Illuminate\\Pipeline\\{closure}",
        "class": "Illuminate\\Pipeline\\Pipeline",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
        "line": 167,
        "function": "handle",
        "class": "App\\Http\\Middleware\\SentryContext",
        "type": "->"
      },
      {
        "file": "/app/app/Http/Middleware/ApiKey.php",
        "line": 40,
        "function": "Illuminate\\Pipeline\\{closure}",
        "class": "Illuminate\\Pipeline\\Pipeline",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
        "line": 167,
        "function": "handle",
        "class": "App\\Http\\Middleware\\ApiKey",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php",
        "line": 41,
        "function": "Illuminate\\Pipeline\\{closure}",
        "class": "Illuminate\\Pipeline\\Pipeline",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
        "line": 167,
        "function": "handle",
        "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php",
        "line": 59,
        "function": "Illuminate\\Pipeline\\{closure}",
        "class": "Illuminate\\Pipeline\\Pipeline",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
        "line": 167,
        "function": "handle",
        "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
        "line": 103,
        "function": "Illuminate\\Pipeline\\{closure}",
        "class": "Illuminate\\Pipeline\\Pipeline",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
        "line": 687,
        "function": "then",
        "class": "Illuminate\\Pipeline\\Pipeline",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
        "line": 662,
        "function": "runRouteWithinStack",
        "class": "Illuminate\\Routing\\Router",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
        "line": 628,
        "function": "runRoute",
        "class": "Illuminate\\Routing\\Router",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
        "line": 617,
        "function": "dispatchToRoute",
        "class": "Illuminate\\Routing\\Router",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
        "line": 165,
        "function": "dispatch",
        "class": "Illuminate\\Routing\\Router",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
        "line": 128,
        "function": "Illuminate\\Foundation\\Http\\{closure}",
        "class": "Illuminate\\Foundation\\Http\\Kernel",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
        "line": 21,
        "function": "Illuminate\\Pipeline\\{closure}",
        "class": "Illuminate\\Pipeline\\Pipeline",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
        "line": 167,
        "function": "handle",
        "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
        "line": 21,
        "function": "Illuminate\\Pipeline\\{closure}",
        "class": "Illuminate\\Pipeline\\Pipeline",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
        "line": 167,
        "function": "handle",
        "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
        "line": 27,
        "function": "Illuminate\\Pipeline\\{closure}",
        "class": "Illuminate\\Pipeline\\Pipeline",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
        "line": 167,
        "function": "handle",
        "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
        "line": 63,
        "function": "Illuminate\\Pipeline\\{closure}",
        "class": "Illuminate\\Pipeline\\Pipeline",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
        "line": 167,
        "function": "handle",
        "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
        "type": "->"
      },
      {
        "file": "/app/vendor/fruitcake/laravel-cors/src/HandleCors.php",
        "line": 37,
        "function": "Illuminate\\Pipeline\\{closure}",
        "class": "Illuminate\\Pipeline\\Pipeline",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
        "line": 167,
        "function": "handle",
        "class": "Fruitcake\\Cors\\HandleCors",
        "type": "->"
      },
      {
        "file": "/app/vendor/fideloper/proxy/src/TrustProxies.php",
        "line": 57,
        "function": "Illuminate\\Pipeline\\{closure}",
        "class": "Illuminate\\Pipeline\\Pipeline",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
        "line": 167,
        "function": "handle",
        "class": "Fideloper\\Proxy\\TrustProxies",
        "type": "->"
      },
      {
        "file": "/app/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Middleware.php",
        "line": 46,
        "function": "Illuminate\\Pipeline\\{closure}",
        "class": "Illuminate\\Pipeline\\Pipeline",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
        "line": 167,
        "function": "handle",
        "class": "Sentry\\Laravel\\Tracing\\Middleware",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
        "line": 103,
        "function": "Illuminate\\Pipeline\\{closure}",
        "class": "Illuminate\\Pipeline\\Pipeline",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
        "line": 140,
        "function": "then",
        "class": "Illuminate\\Pipeline\\Pipeline",
        "type": "->"
      },
      {
        "file": "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
        "line": 109,
        "function": "sendRequestThroughRouter",
        "class": "Illuminate\\Foundation\\Http\\Kernel",
        "type": "->"
      },
      {
        "file": "/app/public_html/index.php",
        "line": 66,
        "function": "handle",
        "class": "Illuminate\\Foundation\\Http\\Kernel",
        "type": "->"
      }
    ]
  },
  "headers": {...},
  "request": {...},
  }
}`

### Expected behaviour
response 200 and test is deleted

### Any other useful information
This is a new behavior, it was correctly working in the past...
nodeJS v12.14.0

**Comment by josephwynn-sc** [comment]
Hey, thanks for reporting this! I believe the issue should be resolved now. Please let me know if not, and I will reopen this issue.
