### ISSUE TITLE
Site is not showing data in Opera

### ISSUE THREAD

**Issue by pcvandamcb** [SpeedCurve-Metrics/SpeedCurve#22]
I'm using Opera 31 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36 OPR/31.0.1889.174)

The graphs are not showing data. It's giving:
(index):1314 Request failed: parsererror

Which seems to be a third-party ajax request.

**Comment by zeman** [comment]
This is probably an account specific issue. Please email support@speedcurve.com with your account details.
