### ISSUE TITLE
User agent doesn't include "PTST/SpeedCurve"

### ISSUE THREAD

**Issue by abelhbeyene** [SpeedCurve-Metrics/SpeedCurve#222]
### Issue type

  - [ ] Feature request
  - [x] Bug report
  - [ ] Question (please email questions to support@speedcurve.com)

### Current behaviour

According to the docs when running a synthetic test the user agent of the browser includes "PTST/SpeedCurve" which can be used to exclude from analytics.
Stated here: https://support.speedcurve.com/en/articles/74072-how-do-the-browser-testing-agents-work

However, we have found that this is not the case. The user agent is only the following:
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"

Here is an example test: https://wpt.speedcurve.com/jsonResult.php?test=210609_AP_90635def31962624c81ab32f02179811

Search for the user agent in the above json and you will see it doesn't include the string "PTST/SpeedCurve"

### Expected behaviour

The user agent should be:
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36 PTST/SpeedCurve"

### Any other useful information

All the criteria of the test can be seen in the JSON link shared above.

**Comment by zeman** [comment]
It looks like just the very first request which is an OCSP request doesn't include "PTST/SpeedCurve" in the UA string. Request 2 to your actual page does. I don't believe we can override the UA string for OCSP requests. Here's more background on managing [OCSP requests.](https://support.speedcurve.com/en/articles/877586-ocsp-requests)

Also the JSON is encoded so you'd need to search for "PTST\/SpeedCurve".

<img width="963" alt="Screen Shot 2021-06-15 at 11 56 46 AM" src="https://user-images.githubusercontent.com/204268/121973173-c6f88700-cdd0-11eb-90e0-dc604296efda.png">

**Comment by wildlyinaccurate** [comment]
> Also the JSON is encoded so you'd need to search for "PTST/SpeedCurve".

GitHub escaped the backslash so just to clarify, you need to search for `PTST\/SpeedCurve`
