### ISSUE TITLE
unload event handler is preventing bfache

### ISSUE THREAD

**Issue by kevinfarrugia** [SpeedCurve-Metrics/SpeedCurve#224]
### Issue type

  - [ ] Feature request
  - [x] Bug report
  - [ ] Question (please email questions to support@speedcurve.com)

### Current behaviour

Pages which include the LUX (RUM) script are not able to be stored in the [bfcache](https://web.dev/bfcache/) because of the use of the `unload` event handler.

I created a sample page which works well with bfcache: https://kevinfarrugia.github.io/bfcache/ . This can be tested using Chrome DevTools new Back/forward cache pane or using the [persisted](https://developer.mozilla.org/en-US/docs/Web/API/PageTransitionEvent/persisted) property on the `pageshow` event.

```
window.addEventListener('pageshow', function(event) {
  if (event.persisted) {
    console.log('Page was loaded from cache.');
  }
});
```

![Screenshot from 2022-02-08 10-12-53](https://user-images.githubusercontent.com/8075326/152956198-3daee475-2afc-404b-91df-e7a560077ba4.png)

I created two copies of the same page ([/unload](https://kevinfarrugia.github.io/bfcache/unload) and [/lux](https://kevinfarrugia.github.io/bfcache/lux)). The first contains the following script:

```
    <script>
      window.addEventListener("unload", () => {
        console.log("Going...going...gone!");
      });
    </script>
```

and the latter imports a random lux.js file from SpeedCurve.

Both pages cannot be stored in the bfcache.

![Screenshot from 2022-02-08 10-19-28](https://user-images.githubusercontent.com/8075326/152956255-7829bb97-5af6-4160-bd6a-042ece78fa50.png)

### Expected behaviour

SpeedCurve shouldn't be stopping bfcache and perhaps the `unload` event could be replaced by the `pagehide` event.

**Comment by andydavies** [comment]
Thanks for raising this @kevinfarrugia 

We're actively working on removing the `unload` handler so that the script doesn't interfere with `bfcache` processing

The updated RUM script is still in testing but we'll update you when we release it

**Comment by kevinfarrugia** [comment]
@andydavies I believe this was solved https://support.speedcurve.com/changelog/rum-update-luxjs-v300
