### ISSUE TITLE
Throttling

### ISSUE THREAD

**Issue by callumacrae** [SpeedCurve-Metrics/SpeedCurve#23]
I think this is a feature request (or I'm missing something).

Is it possible to throttle the connection speed of the test? The majority of our users are using phones, so I'd like to throttle the connection to a fast 3G connection. Is that possible?

**Comment by stevesouders** [comment]
You can do this in the settings page for the Region. The downside of this is ALL tests in that region share the same bandwidth settings. We're working on new settings UI that will allow you to set the bandwidth connections at the Site level - so you could have a Site that was just for 3G.

**Comment by callumacrae** [comment]
Thanks :)
