### ISSUE TITLE
Reported numbers in benchmark varies, depending on which sites are selected

### ISSUE THREAD

**Issue by oskarml** [SpeedCurve-Metrics/SpeedCurve#27]
When looking at a benchmark, and including "all sites" or just one, the reported numbers for that one site is not the same.
Compare:
All sites:
https://speedcurve.com/hth/benchmark/a/4/a/2/7/backend/1z7x98z7ulkg8h4ihfrn34pks0wuwt/
Unoform backend is: 0,33s
Unform only:
https://speedcurve.com/hth/benchmark/11/4/a/2/7/backend/1z7x98z7ulkg8h4ihfrn34pks0wuwt/
Unoform backend is: 0,29s

Same problem regardless of which metric is viewed.
The Unoform site has been added to the benchmark later, so it does not have the full data range; still, the calculations should output the same number - now i dont know which one is correct.

**Comment by zeman** [comment]
The "All Sites" option has now been removed.
