### ISSUE TITLE
API /tests: day and detail page disagree

### ISSUE THREAD

**Issue by mistergaskill** [SpeedCurve-Metrics/SpeedCurve#28]
When I query the /tests API the day always seems to be one day ahead. The test:
{'browser': 'Firefox', 'byte': 1648, 'browser_version': '40.0.2.5702', 'requests': 272, 'dom': 7949, 'speedindex': 4950, 'run': 1, 'location': 'us-west-1', 'test': '151002_NS_b1278cebafa5011c36e7ff5f78b8fed0', 'loaded': 9757, 'day': '2015-10-03', 'size': 2259061, 'pagespeed': 64, 'render': 4455}

shows a day of october 3rd, but the detail page:
https://speedcurve.com/udemy/test/151002_NS_b1278cebafa5011c36e7ff5f78b8fed0/

shows a date of Fri 2nd of Oct 2015 12:43:59 PDT

At first I though it might be an issue of UTC vs PDT, but 12:43 PDT is 19:43 UTC - so they should be on the same day.

It is possible that the test day is in a timezone somewhere east of Iran. If so, what time zone is it? If not, which of these dates is incorrect?

**Comment by mistergaskill** [comment]
Also perhaps these two dates represent different events. If that is the case, what events are they? I assumed they would both be the day/time that the test run started.

**Comment by zeman** [comment]
Funnily enough the "day" is in the New Zealand time zone as that's the first time zone in the world and also where I live which made things simple in the early days of building SpeedCurve. That's why it's a day ahead from PDT.

I'll update the "day" to be in the timezone of the account and also add a UTC timestamp.

Awesome to have you giving the API a good once over. Please don't hesitate to add more bugs like this as you find them.

What are you building?

**Comment by zeman** [comment]
The day value now respects the timezone associated with your API key and can be set on the Team Info page. Also added timezone and UTC timestamp values.

**Comment by mistergaskill** [comment]
Thanks again for looking at these issues.

I'm building an internal dashboard to show our RUM and Synthetic test results side by side so that we can try to get a big picture of how our site is performing and and quickly drill down into the more detailed speedcurve and new relic data to understand why.

Unfortunately, I'm still seeing this issue. the test https://speedcurve.com/udemy/test/151004_30_6e9ffae7f4f903840433f35d630d1fd5/ is coming back with a day of "2015-10-05", when it ran on Sun 4th of Oct 2015 12:13:00 PDT. This is a response from the /urls/ endpoint. Perhaps you updated /sites but not /urls? I'll do more digging to see if I see any changes there.

**Comment by zeman** [comment]
Correct I hadn't updated all the endpoints. Both /sites and /urls have now also been updated and I've added more data so you don't have to necessarily make extra requests to /tests to get extra metrics.

**Comment by mistergaskill** [comment]
Thanks, I can confirm it is working on the /urls/ endpoint.

I'd love to use /sites, but it is mixing together IE, chrome, and firefox results and I want to control for a single browser.
