### ISSUE TITLE
ability to remove a test result

### ISSUE THREAD

**Issue by stevesouders** [SpeedCurve-Metrics/SpeedCurve#29]
"there are times when 
random third party scripts hang, or network issues happen, and we end up 
with a HUGE spike, that skews the scale of our tests. It would be great to 
be able to hide a test from the results for this reason. "

**Comment by stevenmichaelthomas** [comment]
Thanks for logging this @stevesouders '

Here's a sample hanging test, if it helps: https://wpt.speedcurve.com/result/150924_4P_9bb0bb329f6f68d7d03386a4ba5fee2f/

**Comment by stevesouders** [comment]
Another use case: When a test fails it makes the graph look funky (with the red dot on the x-axis). People might want to just delete that outlier.

**Comment by zeman** [comment]
Jonathan, can you please add a "Delete Test" right at the bottom of the Test page.

Use the deleted style from the Settings:

<img width="190" alt="screen shot 2016-05-23 at 9 22 37 am" src="https://cloud.githubusercontent.com/assets/204268/15463238/42a23920-20c8-11e6-848c-d4af04621418.png">

Link can reload the Test page with a delete=1 param, then check user has edit permissions and delete.

We should also delete the corresponding .zip in S3. Let's start a new Test class we can use to start manipulating individual tests and their archives in S3.

**Comment by jonathanhardie** [comment]
Can you point me to some info regarding how you'd go about deleting a zip from S3?  I don't know anything about that side of things.

**Comment by zeman** [comment]
In the run repo (aws/check-archive.php) there's an example of downloading a zip. The $s3 client should have another method for deleting.

**Comment by zeman** [comment]
When you've setup the new method in Wpt.inc assign back to me and I'll do the deleting of the zip in S3.

**Comment by jonathanhardie** [comment]
This has now been implemented and can be tested on dev.speedcurve.com.
I've also actually added the s3 deletion, since that seemed straightforward.  Using the existing TestResult class to stick any utility functions like deleteTest in, rather than creating a new class

**Comment by zeman** [comment]
Note that we have removed the "Delete Test" function as it was causing issues. If there are outliers on a graph you can zoom in on the x and y axis to temporarily hide them.

**Comment by iamnmtd** [comment]
Shame that you have removed this feature. Admin and View Only users need to have a feature to exclude 'bad' tests from charts. If that means a 'logical' delete rather than a 'physical' one thats fine by me - its just removing it from the chart thats important. The zoom in feature isn't enough of a workaround

Ideas I have are

When you click on a test in a chart - as well as view, and note, have exclude and delete options
Like budgets, be able to set a max acceptable test result so that the y-axis is limited to that value. Tests that exceed that value could still be marked on the chart someway but just not made part of the plot line.

**Comment by stevesouders** [comment]
Discussed this a bit. Best solution we came up with is: In the popup menu for a test, add "Hide Test" (along with "View Test" and "Add Note"). Now the problem is how do we UNhide the test?!?! Add an optional setting for "show hidden tests". (This seems a bit silly - why would we show hidden tests? Seems like users would turn this on, go to the dashboard and UNhide the test result they want to recover, then go back and turn this setting off. That's a painful flow. It'd be better if we could bring the option right into the chart. Maybe change the "Notes" link to a hamburger and the dropdown is "hide/Unhide notes" and "hide/UNhide tests".)

**Comment by alexM0** [comment]
How are you getting on with addressing this issue? We recently had an outage which caused a lot of failed tests and rather messy looking graphs:

![failedtests](https://cloud.githubusercontent.com/assets/6106185/20932245/eb2e69a8-bbcb-11e6-8f54-5bbbe497bbc1.JPG)

We would really like to delete these results, or at least hide them. Is there anything we can do?
Do you have an ETA of when you can deliver a new solution to hiding or deleting results?

**Comment by zeman** [comment]
And it's back! You can now delete tests again on the Test dashboard. View a test and then at the bottom right of the dashboard there's a "Delete Test" button.
