### ISSUE TITLE
Speedcurve API not triggering deploy checks

### ISSUE THREAD

**Issue by zenderol** [SpeedCurve-Metrics/SpeedCurve#32]
I’ve noticed today in the team usage chart (https://speedcurve.com/PAGENAME/team/usage/) that the deploy checks, that are triggered after each CI build in our pipeline, are not being triggered anymore (Since October 5th). 

The CI job for triggering the deploy checks did not receive any error response from the API. After manually triggering the deploy check with the API, I also get a successful response:

```
{"status":"success","message":"A deployment has been added and testing is underway.","id":7343,"info":{"tests-added":[{"test":"151006_ZY_0f83ddf6f37a8562d742805092ac4aa9","browser":"chrome","region":"eu-central-1","template":"1529"}],"tests-requested":1,"old-deploys-replaced":["7342"]}}
```

On the “Deploy” Section of the Speedcurve GUI I can see the following message:
![bildschirmfoto 2015-10-08 um 14 15 13](https://cloud.githubusercontent.com/assets/10632238/10366266/79a60030-6dc9-11e5-892a-a709b9543755.png)

The message remains the same without any results. If I trigger an another deploy check using the API, only the build description changes, but it has no effect on the progress.

**Comment by zeman** [comment]
It's looks like the test never completed for that particular deploy and it hung instead. I've cleared the hung deploy and any requests to the API should now be fine.
