### ISSUE TITLE
ability to do a deploy on specific site

### ISSUE THREAD

**Issue by stevesouders** [SpeedCurve-Metrics/SpeedCurve#35]
Right now when using the deploy API or Test Now button the deploy is done on the "main" site. Extend this to allow deploys on any site. 

For the API we should add a "sitename" parameter.

For the Test Now button we need to add Site selection to the GUI, and then the Test Now button will be in the context of a specific Site.

**Comment by stevesouders** [comment]
done

**Comment by nwtn** [comment]
I'm not seeing this option in the Deploy > Test Now GUI. Is it possible to select a site other than the main one?

![screen shot 2015-11-20 at 2 52 19 pm](https://cloud.githubusercontent.com/assets/786799/11310224/5e2aad6c-8f96-11e5-832d-8bf380fd759f.png)

**Comment by zeman** [comment]
We just rolled out the UI for this so you can now add a deploy for any site via the API or Test Now button.

**Comment by nwtn** [comment]
Awesome! Thanks!
