### ISSUE TITLE
Block third party requests checkbox

### ISSUE THREAD

**Issue by stevesouders** [SpeedCurve-Metrics/SpeedCurve#36]
It's important to track the impact of 3rd parties on a website, but sometimes a website owner wants to be able to track their own code without the variability of 3rd parties. For example, you might have a performance budget for JS, but that's really (or might be) for the JS coming from the website owner. 

Let's add a checkbox that when selected will block all third party requests. 

Details:
- "third party" will be any request to a domain that the user has NOT specified as a first party domain in Settings
- "block" is the WebPageTest version of block - I believe it just returns immediately with a 200 but no response body

**Comment by nathanbower** [comment]
This would be a great feature add.

**Comment by fraaalk** [comment]
Any News on this feature? Would be really awesome.

**Comment by kennydee** [comment]
How will you implement that ?

An option on each template : 

* To test only in blocking mode (no change on the number of run needed)
* Or to allow both tests (with and without blocking) (which will double the number of run needed)

The second option open a lot of good opportunity i think.

* Compare on the details screen, stripfilm, and each graph, with or without blocking. You also could compare the two waterfall (as WPT do)
* See evolution on both side
* See how 3rd party impact start render ...
* ...

**Comment by stevesouders** [comment]
You can now do this with the Block Third Party script template: https://speedcurve.com/blog/pwa-performance/
