### ISSUE TITLE
budgets for custom metrics

### ISSUE THREAD

**Issue by stevesouders** [SpeedCurve-Metrics/SpeedCurve#38]
Add the ability to set performance budgets based on custom metrics.

**Comment by nathanbower** [comment]
+1  this would be great to have.

**Comment by jonathanhardie** [comment]
This is a thing in the current settings code.  Is it not being exposed in the UI yet?

**Comment by zeman** [comment]
Correct haven't added it to the UI yet but hope to do that over the next
few days or next week. Can you add some manual row to test with in the
meantime?

**Comment by zeman** [comment]
Custom metrics are now available when adding a budget. You can find them under the "Metrics" options.
