### ISSUE TITLE
Responsive: Support selection of a non-main site

### ISSUE THREAD

**Issue by lostthetrail** [SpeedCurve-Metrics/SpeedCurve#4]
Much like the site tab now allow the selection of a non-main site, it would be great if the responsive tab could support this as well.

**Comment by stevesouders** [comment]
Definitely agree. It's a little more complicated because this increases the number of checks that are performed, so we want users to have the ability to enable/disable responsive checking at the individual Site level.

**Comment by lostthetrail** [comment]
Understood. The toggle seems to be "treat as main site" or "treat as secondary site".

**Comment by stevesouders** [comment]
Would be nice to do this:
   - add the responsive checkbox to the settings page for ALL sites (on by default for new users)
   - make sure the test queueing code is looking for this responsive flag and adding viewports correctly
   - change the Responsive dashboard UI to allow picking any site that **has responsive turned on** (or maybe allow picking all sites and if the checkbox isn't turned on relay that message)

**Comment by stevesouders** [comment]
resolved in new Settings UI rolling out next week
