### ISSUE TITLE
No 'Access-Control-Allow-Origin' header using REST API

### ISSUE THREAD

**Issue by joacim-boive** [SpeedCurve-Metrics/SpeedCurve#40]
Trying to do an AJAX request to build my own dashboard, where SpeedCurve is one datasource.

"Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:63342' is therefore not allowed access."

I'm aware that I can use my own proxy server, but that's not ideal.
(My URL http://localhost:63342 is of course only temporary.)

When will the header be added?
Access-Control-Allow-Origin: *

**Comment by mnovinger** [comment]
Any chance this issue will get fixed?

**Comment by zeman** [comment]
Just added the extra header. Give it another spin now.
