### ISSUE TITLE
Dashboards from different team accounts loads the same dashboard

### ISSUE THREAD

**Issue by sabbaspoursani** [SpeedCurve-Metrics/SpeedCurve#41]
We're trying to add the SpeedCurve charts on our monitoring screens. When we add a dashboard from team "x" on one tab and another dashboard from team "y" on another tab, it doesn't work and just loads the same dashboard for both tabs.

**Comment by zeman** [comment]
We rolled out a fix for this a few days ago. Can you please give it another try.
