### ISSUE TITLE
Adding/setting a test time results in double tests

### ISSUE THREAD

**Issue by brysongilbert** [SpeedCurve-Metrics/SpeedCurve#42]
We've found that setting a non-default test time (say, 10:00) results in tests being run at both 10:00 and 12:00. Then, trying to delete the 10:00 time results in an error ("Sorry, this is your main testing time and it can't be deleted."). In other words, running a single test per day at a time other than 12:00 seems to be impossible.

cc @stevenmichaelthomas

**Comment by stevesouders** [comment]
We require all accounts to have at least *one* test time. Instead of deleting the "12:00" test time, you can instead edit it to be "10:00" or any time you prefer.
