### ISSUE TITLE
hide ALL site data in Benchmark

### ISSUE THREAD

**Issue by stevesouders** [SpeedCurve-Metrics/SpeedCurve#44]
In the Benchmark dashboard, it's possible to click on a Site name at the top and have that site's trend line hidden in the chart. In addition to hiding the trend line, It would be good to also hide that site's other data from the dashboard, specifically, filmstrip and global benchmark.

**Comment by zeman** [comment]
This UI doesn't exist any more. You can click on the legend alongside each graph to control visibility.
