### ISSUE TITLE
Bug in content request count and size

### ISSUE THREAD

**Issue by theoephraim** [SpeedCurve-Metrics/SpeedCurve#45]
Seems there are some bugs on your side for counting the requests and their size.
The test appears to be normal, but that data is lost.

![site___speedcurve](https://cloud.githubusercontent.com/assets/1158956/11256815/1612ac58-8e1c-11e5-85af-3fba9dd735c2.png)

**Comment by zeman** [comment]
There have been some bugs with the latest WebPageTest agents which have caused the missing requests data. We've been working closely with Pat from WebPageTest.org on the issues and they should now be resolved for any tests going forward.

**Comment by theoephraim** [comment]
thanks! just wanted to make sure you were aware.
