### ISSUE TITLE
Overwritten user timing marks are incorrectly reported

### ISSUE THREAD

**Issue by laurentgoudet** [SpeedCurve-Metrics/SpeedCurve#46]
See full explaination here: https://github.com/WPO-Foundation/webpagetest/issues/539. As a result, these user timing marks do not reflect the reality as seen here: https://speedcurve.com/freelancer/test/151130_SY_eed7959417c1bd5bd6b586419a916e86/. Since the "last value" of these user timing marks are exported by the WPT instances, would it be possible to fix it in SpeedCurve while WPT gets fixed? Thanks!

**Comment by laurentgoudet** [comment]
Looks like the issue is simply Steve's technique not being accurate (see WPO-Foundation/webpagetest#539 for the details). I still don't quite get the extreme spikyness of the "cover image" user timing mark in https://speedcurve.com/freelancer/site/1/12/chrome/1/30/ though.

**Comment by stevesouders** [comment]
As pointed out in https://github.com/WPO-Foundation/webpagetest/issues/539 this is not a bug but instead is the first view and repeat view stats.
