### ISSUE TITLE
Charts annotated with deployment info are very difficult to read on sites with frequent deploys

### ISSUE THREAD

**Issue by bregenspan** [SpeedCurve-Metrics/SpeedCurve#48]
After adding deploys to my project's SpeedCurve, I see the following, which is a little hard to read :) :
<img width="1229" alt="screen shot 2015-12-03 at 4 54 23 pm" src="https://cloud.githubusercontent.com/assets/237410/11575373/a2ea985c-99de-11e5-86f4-cf05b0a993df.png">

**Comment by zeman** [comment]
We're planning on adding some controls to show/hide labels in this situation. Also you can click drag to zoom in on any part of the graph in the meantime to make it more manageable.

**Comment by zeman** [comment]
We now have show/hide controls for notes so at least you can turn off all notes to see the underlying data.
