### ISSUE TITLE
Ability to make different group of websites

### ISSUE THREAD

**Issue by kennydee** [SpeedCurve-Metrics/SpeedCurve#5]
Hi,

First, thanks for the speedcurve product :)

We got several websites to maintain, and each of one have it's own templates and competitors.
It's frustrating for now because everything is mixed, and the main site has to have all templates ...
And we don't want to create one speedcurve account for each website.

A possibility to made multiple group of website, each one with a main website and his competitors will be a huge features for us !

Thanks again

**Comment by stevesouders** [comment]
We're actually working on this now. I created issue #7 to track the progress of this feature.

**Comment by kennydee** [comment]
Thanks Steve !
This is huge to hear you working on That :)
Hope to see u at velocity NY this year
