### ISSUE TITLE
[Benchmark] Filmstrip not refreshed when switching between templates

### ISSUE THREAD

**Issue by laurentgoudet** [SpeedCurve-Metrics/SpeedCurve#50]
In the "Benchmark" section, when switching between templates, the filmstrip view is greyed and not refreshed. Reloading the page refreshes the filmstrip but is annoying :).

<img width="1271" alt="screen shot 2015-12-04 at 10 46 28 am" src="https://cloud.githubusercontent.com/assets/2169585/11586580/655f581a-9a74-11e5-8d87-7ab1a7e3bfad.png">

**Comment by zeman** [comment]
Also check thumbnails are https.

**Comment by stevesouders** [comment]
fixed
