### ISSUE TITLE
Update API documentation for /v1/tests/ sample data

### ISSUE THREAD

**Issue by itsmemattchung** [SpeedCurve-Metrics/SpeedCurve#51]
**"timestamp"** attribute is missing from the documentation's sample data (https://api.speedcurve.com/#get-a-test).  

We're using sample data for running unit tests and noticed the documentation error. The timestamp is *actually* available as part of the JSON response

## Documentation sample data
https://github.com/itsmemattchung/speedcurve.py/blob/master/tests/unit/example_data/test.json

## Real integration test
https://github.com/itsmemattchung/speedcurve.py/blob/master/tests/cassettes/Speedcurve_test.json

**Comment by zeman** [comment]
Updated. Thanks for spotting this and also building a python wrapper. Don't hesitate to sing out if you spot any other issues with the API.
