### ISSUE TITLE
[API] Pass a hyperlink as a deploy note

### ISSUE THREAD

**Issue by zenderol** [SpeedCurve-Metrics/SpeedCurve#52]
While triggering the deploy checks using the Speedcurve API it would be very useful to pass a hyperlink inside the build note. Currently the hyperlinks are escaped by the API. For example a link to the build commit information on github would be passed as follows:

```
//grunt-curl
 src: {
       url: 'https://api.speedcurve.com/v1/deploy',
       auth: {
          user: env.sc_user
          password: env.sc_pass
       },
       method: 'POST',
       form: {'note': 'Commit: <a href =\"https://github.com/my_organization/project/commit/'+commit_hash+'\"'+commit_hash+'</a>'}
      }
```

This way a build note in the Speedcurve graphs would become a link to the build commit description and would improve the process of finding causes of performance regressions.

**Comment by zeman** [comment]
We could add extra "link" and "link_title" fields rather than allow html.

**Comment by zenderol** [comment]
great idea, thank you!
