### ISSUE TITLE
move data across teams

### ISSUE THREAD

**Issue by stevesouders** [SpeedCurve-Metrics/SpeedCurve#54]
Test results are associated with one and only one team but there are situations where customers might want to move the results to a new team. 

Imagine that an organization starts with team A. Team A is testing URL 1 for the past year. But then a new team is created, team B, that takes over responsibility for URL 1, so URL 1 is *removed* from A's settings and added to B's. Right now, team B will NOT see any history for URL 1 (because all the previous test results belong to team A). 

Since teams A and B are in the same organization, it should be possible to move those previous results so that they are associated with team B instead of team A.

**Comment by zeman** [comment]
Customers can request that data be moved/copied between teams by contacting support@speedcurve.com.
