### ISSUE TITLE
share results across multiple teams

### ISSUE THREAD

**Issue by stevesouders** [SpeedCurve-Metrics/SpeedCurve#55]
It would be nice if different teams in the same organization could share test results if they're both monitoring the same URL. 

This might lead to some confusion. For example, suppose teams A and B (in the same organization) are monitoring URL 1. Team A checks it at 9am, and team B checks it at 10am. If we share test results across teams, when members of the team view a timeline of results there will be twice as many results as expected - because they're viewing their own scheduled test results as well as the other team's test results.

**Comment by stevesouders** [comment]
Billing and budgets would need to be addressed. Right now an organization's budget is split across the teams. We'd have to figure out which team is charged for a shared URL. This would only be an issue if the test conditions were exactly the same across both teams - the test time, browser, region, etc.

**Comment by zeman** [comment]
We've focused on preserving the history of a URL rather than sharing history between Sites, so we'll no longer be able to do this.
