### ISSUE TITLE
[Webhook] Possibility to send notifications to multiple Slack channels.

### ISSUE THREAD

**Issue by zenderol** [SpeedCurve-Metrics/SpeedCurve#57]
Currently it is only possibly to configure a single Slack channel for receiving notifications using webhooks. If multiple Slack webhooks are set up using the Speedcurve user interface, only the first webbhook's url is stored, the url of the second webhook is being overridden by the first one.

Is there a possibility to fix this minor issue?

**Comment by zeman** [comment]
Fixed.
