### ISSUE TITLE
Login URL

### ISSUE THREAD

**Issue by zeman** [SpeedCurve-Metrics/SpeedCurve#59]
Some third party login services like https://www.okta.com/ need a specific login URL. We currently have a popup on any page but also need a specific login page.

**Comment by zeman** [comment]
Jonathan, can you add a new login page at /speedcurve.com/login/ that copies the functionaility that's in the modal popup.

**Comment by jonathanhardie** [comment]
I've assumed it's okay if the new page still relies on JS, and have done the simplest possible thing, which is to make sure the login prompt always gets displayed without interaction if the url is /login/

Let me know if my assumptions are wrong!

**Comment by zeman** [comment]
Yep, I think that will do the trick. Let's get more feedback from people as they try it with their systems.
