### ISSUE TITLE
Failing api authentication probably shows me too much infomation

### ISSUE THREAD

**Issue by mnovinger** [SpeedCurve-Metrics/SpeedCurve#60]
I incorrectly authenticated to the api with my login name (instead of my api key) and I get a Whoops! container with lots of database and coding debugging information. I'm assuming you don't want this and rather an error message letting me know my authentication was incorrect. Thanks!

<img width="1440" alt="speedcurve-error" src="https://cloud.githubusercontent.com/assets/98398/13360882/a728626e-dc78-11e5-9813-41af757f5d47.png">

**Comment by zeman** [comment]
Thanks! Fixed now.
