### ISSUE TITLE
send notification after N failures

### ISSUE THREAD

**Issue by stevesouders** [SpeedCurve-Metrics/SpeedCurve#61]
If a customer runs many tests during the day, the fail-pass-fail-pass flapping can be a bit chatty. One customer requested that notifications only be sent after N tests-in-a-row fail/pass.

**Comment by jonathanhardie** [comment]
I added this, but we don't expose it anywhere at the moment.  There is a column in performance_budgets called "trigger_after_n_tests" which has a default of 1, and you can set this higher to test out the functionality.

**Comment by stevesouders** [comment]
I can't find them in intercom. Closing until they ping us again.
