### ISSUE TITLE
checkbox to preserve UA string

### ISSUE THREAD

**Issue by stevesouders** [SpeedCurve-Metrics/SpeedCurve#62]
Similar to public WebPageTest, have a checkbox to preserve original UA string (ie, do NOT add "PTST"). Some services (such as ads) serve different content if PTST is present.

Note that this same behavior can be achieved by using scripting, although that scripted URL could only be run on one browser (since the UA string in the script is specific to a single browser).

**Comment by zeman** [comment]
This request to make all WPT UI options available via scripting would help with this. https://github.com/WPO-Foundation/webpagetest/issues/606

**Comment by zeman** [comment]
The script command ```setKeepUA	1``` can now be added to WPT scripts to control this option.

http://support.speedcurve.com/knowledgebase/articles/611454-adding-webpagetest-scripts-to-urls
