### ISSUE TITLE
ability to enable/disable templates

### ISSUE THREAD

**Issue by msc-travelmarket** [SpeedCurve-Metrics/SpeedCurve#64]
It would be incredibly helpful, if templates could be enabled/disabled.

Say I am running a number of templates to test various things.
To save on my checks I would like to not run these, while I change my code - but I want to run them again later, once my changes have been published.

As it is now, I would have to delete the templates and then recreate them again later.

**Comment by kennydee** [comment]
Maybe adding the possibility to test some url only once could do the job ?
A Webpagetest like screen, restricted to your website, where you could check an url for a website already configured, without being forced to add this url to the template.
The screen will list all previously tested Url to show the detail of the test.

**Comment by zeman** [comment]
Pausing the URL makes sense, that way you can still see the history without new tests running.

**Comment by alexM0** [comment]
Hey,

I'd also like to "vote" for this "issue" to become live. I sent a similar email yesterday to support asking if we could stop tests for a site, but still keep the results viewable. A pausing feature would be great. Some of the projects we work on have a limited timeframe - by that I mean the sites may be up for a month and then they get taken down again. It would still be good to view these results, perhaps in some sort of archive - it's important we learn from mistakes that are made. 

Perhaps allow users to select no test times under Settings / Sites / Sitename.

**Comment by zeman** [comment]
You can now pause the testing on a site by removing all the test times. More details here...

http://support.speedcurve.com/settings/how-do-i-pause-testing-for-a-site
