### ISSUE TITLE
Incorrect identification of Blocking CSS & JS 

### ISSUE THREAD

**Issue by andydavies** [SpeedCurve-Metrics/SpeedCurve#65]
(@stevesouders this is the issue I mentioned at dinner the other night)

This originally came up on Slack where someone was trying to compare the output of PSI and SpeedCurve

Looking at this test: https://speedcurve.com/thequint-1/test/160223_6G_389574d19c46a6459679fd7ea60be9f5/ 

SpeedCurve identifies there are 3 blocking CSS, but only marks one as blocking in the waterfall, and 8 blocking scripts but only shows 5 in the waterfall (or maybe they are too narrow to see the marks)

Looking at the source of the page captured in the WPT test underneath (https://wpt.speedcurve.com/details.php?test=160223_6G_389574d19c46a6459679fd7ea60be9f5&run=1) I'm not sure the blocking resources are being detected correctly.

From my reading of the code the Google fonts CSS should be marked as blocking to, and of the JS side the AddThis snippet should also be marked as blocking.

I think there may be a second issue where the waterfall may give a confusing picture - all the blocking scripts are way down the document (line 1000+ I think) yet because the pre-loader finds them early they appear at the top of the waterfall even though they don't block rendering (I haven't verified that) - this may give people the impression that the resources are on the Critical Rendering Path when they aren't (not sure how you solve that ATM).

**Comment by stevesouders** [comment]
I just tried this and it appears to be working as expected. In the current version of this page, there are 3 stylesheets. Two of those are LINK elements in the main document and are shown correctly in the waterfall with the hash pattern. The third is in an iframe. Since it's NOT a blocking stylesheet, we don't show it as blocking.
