### ISSUE TITLE
Budget 500 Error

### ISSUE THREAD

**Issue by AdamBarnwell** [SpeedCurve-Metrics/SpeedCurve#66]
Trying to delete any of my budget & alerts causes a 500 Error (and doesn't delete the budget). Editing a budget and clicking save ends up duplicating said budget. :/

**Comment by zeman** [comment]
Hi Adam,

Can you please give me an example of a budget you'd like to delete so that I can test it out in your account and see what's going wrong.

Cheers,
Mark

**Comment by zeman** [comment]
Give it another spin now. Should be fixed.

**Comment by AdamBarnwell** [comment]
@zeman all fixed, thank you!
