### ISSUE TITLE
Incorrect SpeedIndex Units and Context

### ISSUE THREAD

**Issue by johndjameson** [SpeedCurve-Metrics/SpeedCurve#67]
It looks like SpeedIndex values are being given in seconds and reported alongside other significant times.

![site speedcurve 2016-03-07 11-35-32](https://cloud.githubusercontent.com/assets/4504978/13575823/cd47657a-e458-11e5-84ca-57e4e02e3361.png)

This behavior seems consistent across all chart types.

![responsive speedcurve 2016-03-07 11-29-26](https://cloud.githubusercontent.com/assets/4504978/13575635/f051ab12-e457-11e5-82bb-b2ccef95fc1b.png)

**Comment by zeman** [comment]
While Speedindex is not a specific point in time, it is measured in milliseconds. We've decided to represent it in seconds so we can show it in context alongside other important measures of user experience like Start Render and Visually Complete.

More background on SpeedIndex here: https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index

**Comment by joacim-boive** [comment]
I'm sorry I don't agree with that decision.

Where does the visual completing of the formula come into the picture:
 IntervalScore = Interval * (1.0 - (**Completeness**/100))

Then we have the fact that now we don't have any history to compare our progress with.
