### ISSUE TITLE
Timing charts incorrectly using stacked visualisation

### ISSUE THREAD

**Issue by jon-nunan** [SpeedCurve-Metrics/SpeedCurve#68]
Values in the timing graph appear to be stacked on top of each other instead of overlayed.
e.g. below the values are Start: 3.3s Load 7.1s & Complete 12.8s.
![speedcurve-stack](https://cloud.githubusercontent.com/assets/124704/13587550/c3e9826c-e514-11e5-81d7-8635ed94c8f4.png)

Complete 12.8s is an absolute value, not the difference between it and load which is what the chart seems to be implying.

**Comment by zeman** [comment]
Fixed. Thanks for spotting that one!
