### ISSUE TITLE
Site order

### ISSUE THREAD

**Issue by jon-nunan** [SpeedCurve-Metrics/SpeedCurve#69]
Before the last update, the sites seemed to be ordered by the order they were added.
After the update it seems to have gone to alphabetical order, this is a little annoying as now the default is not our primary site for the account.  Have worked around this by renaming the site profile "AA <sitename>"

**Comment by isurfbecause** [comment]
Thanks @jon-nunan for the tip.

**Comment by zeman** [comment]
We've now removed any concept of a "main" site and all your sites are treated the same. We added session tracking yesterday than now remembers what your selected options are as you move across dashboards. Once you select a site you should get the same site when you refresh the page or move between dashboards.
