### ISSUE TITLE
ability to manage multiple accounts 

### ISSUE THREAD

**Issue by stevesouders** [SpeedCurve-Metrics/SpeedCurve#7]
Current accounts are good for organizations that run a single website: they can create a "main" SpeedCurve Site for the production website, and other Sites for competitors and staging servers. But this account structure doesn't work easily for larger organizations that have multiple properties (media, retail, Yahoo, etc). A workaround is for them to create a separate account for each property - but that's a management hassle. 

Instead, we need a way to bundle multiple accounts into a mega account - with centralized billing, permissions, logins, etc.

**Comment by kennydee** [comment]
Is it possible to have update on this issue ? this is critical for us :)

Thanks

**Comment by stevesouders** [comment]
fixed and available in Enterprise Plans
