### ISSUE TITLE
Periodically executed tests comparison

### ISSUE THREAD

**Issue by 1000ch** [SpeedCurve-Metrics/SpeedCurve#74]
There are no way to compare tests executed periodically on "Site" tab.
Do you have a plan to implement the feature to compare tests not only on "Deploy"?

**Comment by zeman** [comment]
Yes, we plan to have a feature that would let you choose any two tests across any of the dashboards and then compare them. A little like a shopping cart where you can collect multiple tests and then do a diff on them. Don't have an ETA on this feature yet.

**Comment by toke182** [comment]
Any news about this feature, I think is key

**Comment by zeman** [comment]
We don't have a snazzy UI to do this yet but you can now compare any tests using the test ids. Here's how...

https://support.speedcurve.com/using-synthetic/compare-metrics-filmstrips-video-for-any-two-tests
