### ISSUE TITLE
Add custom metrics to test API responses, or expose the site-data.php endpoint

### ISSUE THREAD

**Issue by mnovinger** [SpeedCurve-Metrics/SpeedCurve#77]
Hi, I was hoping to invert the graphs on your dashboard to show each metric graphed across all our sites, rather than all the metrics for one site. We want to see how different sites measure for each of our custom metrics. From what I can see in the docs the api doesn't expose the custom metrics, but the endpoint that provides the data for the dashboard graphs does.

Thank you!

**Comment by zeman** [comment]
The [urls/{url_id} endpoint](https://api.speedcurve.com/#get-all-tests-for-a-url) now also lists an custom metrics found on the URL during testing.
