### ISSUE TITLE
Speed index not displayed in Benchmark screen

### ISSUE THREAD

**Issue by amarlot** [SpeedCurve-Metrics/SpeedCurve#78]
Hi team,
If I go to this page and select speedIndex. I should get a number between 3000 and 9000 and I got a number of s so it's not speed index.
URL : https://speedcurve.com/la-redoute-fr/benchmark/?u=4198&b=chrome&r=eu-west-1&d=30&m=speedindex

Could you check please,
Thanks,
Alex

**Comment by amarlot** [comment]
Same things here : https://speedcurve.com/la-redoute-fr/site/?s=1576&u=4202&b=chrome&r=eu-west-1&d=30

**Comment by amarlot** [comment]
Hi Team,

Could you confirm it's a bug or is it a new metrics calculated from the speed index ? If yes could you explain it to us.

Thanks in advance,
Alexandre

**Comment by zeman** [comment]
There's more background in this blog post about the changes. https://speedcurve.com/blog/measuring-the-user-experience/
