### ISSUE TITLE
API - Meaning of median array on sites requests is unclear

### ISSUE THREAD

**Issue by neerolyte** [SpeedCurve-Metrics/SpeedCurve#80]
The [sites request](https://api.speedcurve.com/#get-all-sites) returns a median array, which appears to be just a set of tests the same as you would get from the urls request - but if you have a site with multiple URLs there's only one median array and it's not clear if it belongs to one url only or some combination of the two within a test period (i.e if there's 2 URLs do you take the median of all 6 checks?).

It'd be good to explain what it's for, if it's meant to be the median tests for each URL (which makes the most intuitive sense), then there's currently data missing...

**Comment by zeman** [comment]
This is currently the median test result for each day across all urls, browsers and regions. We'll soon be updating the API to bring it more inline with the current dashboards on SpeedCurve and just show a single url, browser and region. You'll then be able to pass in params to select the combo of results you want.

**Comment by mnovinger** [comment]
Thanks for explanation Mark, what's the timeframe for the new API? Also will the url collection include the label for each url?

**Comment by zeman** [comment]
There's now a new [/sites/{site_id} endpoint](https://api.speedcurve.com/#get-site-details-and-settings) that will return the site settings which you can now use to filter the results from the [/url/{url_id} endpoint.](https://api.speedcurve.com/#get-all-tests-for-a-url) Labels are included in both endpoints.
