### ISSUE TITLE
404 on the demos

### ISSUE THREAD

**Issue by danchristian** [SpeedCurve-Metrics/SpeedCurve#81]
https://speedcurve.com/demo/responsive/1/a/1/30/speedindex/39tfnozeq94p1o0hndk1kpbg4vb7cg/

![screen shot 2016-04-07 at 11 14 26](https://cloud.githubusercontent.com/assets/5786541/14348042/eedbf57c-fcb1-11e5-877f-c2dd485e1ff3.png)

**Comment by zeman** [comment]
Yikes! Thanks for that. All fixed.
