### ISSUE TITLE
Site name with apostrophe prevents editing from Setting Screen

### ISSUE THREAD

**Issue by milleba58** [SpeedCurve-Metrics/SpeedCurve#85]
If a site name is added with an apostrophe, future edits to that site are not available.  Additionally, adding URLs to a different site is not possible without editing the DOM to escape the apostrophe.

An example of the issue is available in the site associated with _brooksrunning@soasta.com_

**To reproduce site edit issue:**
1. Log into _brooksrunning@soasta.com_ account
2. Click _Settings_.
3. From _Settings_ dashboard, click _DICK'S_ under _Sites_ list.

Expected:
Site editing page

Actual:
Blank White page

**To reproduce site URL edit issue:**
1. Log into _brooksrunning@soasta.com_ account
2. Click _Settings_.
3. From _Settings_ dashboard, click _ZAPPOS_ Site.
4. From _ZAPPOS_ site properties, click _+ ADD URL_

Expected:
New URL text inputs

Actual:
No visible action on the screen.  However, browser console debugger shows _unexpected identifier_ error related to unescaped apostrophe.  Screenshot below.

<img width="1098" alt="screen shot 2016-05-12 at 09 53 43" src="https://cloud.githubusercontent.com/assets/3752449/15340427/4aa1d63c-1c3e-11e6-8b0c-67238226d750.png">

**Comment by zeman** [comment]
Sorry about that. Fixed now.
