### ISSUE TITLE
Fix SpeedIndex metrics/budgets: It represents a score not a time.

### ISSUE THREAD

**Issue by soneill** [SpeedCurve-Metrics/SpeedCurve#86]
This used to work properly but recently changed. Anything referring to Speed Index should refer to a unit-less score (e.g. 2000) not a time (e.g. 2.0s). Speed Index is not a time. You folks taught me that 👍

**Comment by zeman** [comment]
It is a time so we switched to showing it in context with other time based metrics. More background in this [blog post](https://speedcurve.com/blog/measuring-the-user-experience/).

**Comment by soneill** [comment]
Cool. Thanks for the info. In that case, I think you missed a spot:

An individual test has an "Other Metrics" section at the bottom which contains a unit-less Speed Index, as seen here: 

![screen shot 2016-05-24 at 4 01 06 pm](https://cloud.githubusercontent.com/assets/3769766/15522640/d0d3148e-21c8-11e6-934a-61c342a06414.png)

**Comment by zeman** [comment]
Thanks! Fixed.
