### ISSUE TITLE
Fix Budget Creation bugs

### ISSUE THREAD

**Issue by soneill** [SpeedCurve-Metrics/SpeedCurve#87]
Steps to reproduce: 
1. Create a new budget for a specific Site, URL, Browser, Region, Metric and Threshold in decimal seconds. 
(E.g. Amazon.com, homepage, Chrome, US West Coast, Start Render Time, 2.5 seconds.) 
2. Save the budget. 
3. View the budget on the Site page. 
- Notice that the Start Render Time is floored to the nearest whole second. 
- Expected result: The Start Render Time budget is 2.5 seconds, as entered.
4. View the Budget List on the settings page. 
- Notice that the Budget label/button has no mention of any of the specifics above (site, url, etc) just the Metric. 
- Expected result: The label contains the site, URL, Browser, Region, Metric and Threshold, all if applicable. Make it useful over pretty.
5. Edit the budget 
- Notice that the Site selection was not persisted (now shows "All Sites" in the dropdown) 
- Notice that the Threshold in seconds has been floored to the nearest integer, not remembering the 2.5 seconds as entered.
- Expected Result: The site and threshold are saved as originally entered.

**Comment by zeman** [comment]
Since the URL is more specific than the Site, the budget ignores the Site value. We just need the UI to update the Site select when a URL budget is shown. There's no difference in the underlying budget though.

Jonathan, can you look at the rounding problems please.

**Comment by jonathanhardie** [comment]
I've made it so time-based metrics are now not rounded to integers when added.  @zeman were you going to handle the other UI issues?  I'm not 100% clear from your comment what you'd like to have done there.

**Comment by soneill** [comment]
Thanks for the quick turnaround on that!
The only super annoying outstanding issue would be the labels looking identical on `/settings/#budgets` 
I want to (and can) create separate start render budgets for about 9 pages, on both Chrome (cable) and iPhone (3G), so 18 budgets total, all based on Start Render time.

At the moment it would look like so, but 9 times worse.
![screen shot 2016-05-25 at 2 04 19 pm](https://cloud.githubusercontent.com/assets/3769766/15556291/02b42178-2282-11e6-8042-d7012722aceb.png)

**Comment by zeman** [comment]
They are meant as a quick overview. After you add more than 5 budgets you get a "See More Budgets" link that gives you a full overview of all your budgets and their settings. You can try it out by visiting https://speedcurve.com/mec/settings/allbudgets/

**Comment by soneill** [comment]
👍  I was thinking a table would be great. Thanks!
