### ISSUE TITLE
error with Team invitations

### ISSUE THREAD

**Issue by stevesouders** [SpeedCurve-Metrics/SpeedCurve#88]
When someone gets an email invitation to join a team and they submit the account creation form (with new password) they get a 500 error. In the background the account DID get created, but of course they don't know that. If they try to login it works fine.

To further complicate things, if they start over and click on "Accept Invitation", they get an "Invitation has Expired" message. Instead, they should be told "This invitation was already accepted - please log in."

**Comment by jonathanhardie** [comment]
Fixed, same issue as #379
