### ISSUE TITLE
Ignore browser URL loading label in Start Render time

### ISSUE THREAD

**Issue by soneill** [SpeedCurve-Metrics/SpeedCurve#89]
See image. The tiny browser status message saying "resolving host..." is drawn on the filmstrip, and it seems that the Start Render time is triggered by the difference in frames. The page hasn't started rendering at this time, this is a browser artifact that is interfering with the correct data. 

![screen shot 2016-06-10 at 10 43 57 am](https://cloud.githubusercontent.com/assets/3769766/15973440/48a13dd8-2ef8-11e6-9778-1af643fb1c47.png)

**Comment by zeman** [comment]
This is a bug within the WebPageTest agents. You can track the issue here https://github.com/WPO-Foundation/webpagetest/issues/623

**Comment by zeman** [comment]
@soneill can you email the URL of that particular test through to support@speedcurve.com so I can check if this is still an issue.

**Comment by zeman** [comment]
Unable to find an examples of this still being a problem.
