### ISSUE TITLE
Access to all of the Webpagetest pages on each Speedcurve test

### ISSUE THREAD

**Issue by kennydee** [SpeedCurve-Metrics/SpeedCurve#9]
Hi,
For now, for each tests, we only have access to the "video/compare" section of the corresponding WebPageTest Waterfall. This is really usefull, but it will be much better to have access to all the webpagetest page for all the tests.

It will allow us to enjoy all of the incredible feature packed into WPT (that are not available in SpeedCurve for now) : 
- Domain breakdown
- PageSpeed Score details
- the "View all image" page (incredibly usefull)
- Maybe the video capture ?
- ...

Thanks again for this incredible product :)

**Comment by zeman** [comment]
Thanks for the feedback. It's hidden but you can click on the label next to the beginning of the filmstrip and it will take you to the main result page.

I've also added an extra link on our waterfall page to take you straight there and get all the extra content! We'll be bringing more and more of the data through into the SpeedCurve UI over time.

**Comment by kennydee** [comment]
Huge ! This is perfect. Thanks for the amazing job :)
The more i use SpeedCurve, the more i like it !
