### ISSUE TITLE
add ability to add, remove and view url configuration from the API

### ISSUE THREAD

**Issue by mnovinger** [SpeedCurve-Metrics/SpeedCurve#91]
We have to use WPT scripts in all our tests, and managing the tab delimited configuration across 5-6 sites with 2-4 urls each is error prone and repetitive. We'd much prefer to configure them with an API, than we could version control the configuration and create new tests as needed.

**Comment by zeman** [comment]
We will add this at some point. In the meantime, if you're on an Enterprise plan we do support the bulk import of sites, URLs and settings via JSON.

http://support.speedcurve.com/knowledgebase/articles/917832-bulk-site-settings-import

**Comment by zeman** [comment]
Contact support@speedcurve.com if you want to try the JSON import feature.
