### ISSUE TITLE
[WebPageTest] Chrome Warning Pop-up appears during video recording of the test

### ISSUE THREAD

**Issue by zenderol** [SpeedCurve-Metrics/SpeedCurve#92]
![bildschirmfoto 2016-07-21 um 15 06 35](https://cloud.githubusercontent.com/assets/10632238/17023668/c1ff8a3c-4f54-11e6-98a9-a9dffb1441e3.png)

**Comment by okor** [comment]
Same issue here.

**Comment by zeman** [comment]
We're working with Pat from WebPageTest now to investigate this. It appears to be an issue with Chrome 52 which has just been released in the last day.

**Comment by zeman** [comment]
Pat is aware of the Chrome 52 issue and will work on a fix for the agents asap.

**Comment by zeman** [comment]
We've now rolled out an update to the WPT agents that have a temporary work around. The popup is still there but it is now visible from the very first frame so it no longer affects the start render metric. We expect more updates to the WPT agent over the next couple of days to completely remove the popup.

**Comment by okor** [comment]
@zeman Thank you for the quick actions and updates on this issue : )

**Comment by zeman** [comment]
Pat has used his ninja coding skills to tear the popup out by it's feeble windows roots and we no longer have a popup in our Chrome 52 tests. Thanks @pmeenan

**Comment by okor** [comment]
Thank you @pmeenan and @zeman ! Much appreciated.
