### ISSUE TITLE
Back button wackiness 

### ISSUE THREAD

**Issue by okor** [SpeedCurve-Metrics/SpeedCurve#93]
When using the SpeedCurve UI, if you make the mistake of pressing the back button the results are rarely predictable. Navigation text has "undefined" values, the page content sometimes doesn't change at all ... all manor of strange things. This has been the case for quite some time. It would be great if we could get a better user experience. If this is not immediately obvious for others, check the vox-media account and browse around.

**Comment by zeman** [comment]
Yes, there's some issues with the back button we're working on currently. We recently improved the Dropdown to not show you options that are not available for a particular site but this has broken the back button. If all sites have all settings (labels, regions, browsers) turned on then it works correctly.

**Comment by okor** [comment]
@zeman Understood, thank you sir.

**Comment by zeman** [comment]
We've fixed this and will rollout in the next push.

**Comment by okor** [comment]
Thank you Mark!
