### ISSUE TITLE
Please add "sticky" options

### ISSUE THREAD

**Issue by okor** [SpeedCurve-Metrics/SpeedCurve#94]
When working in the SpeedCurve UI and changing views from one data set to another, the drop down list of options (region, browser, time range, etc) all reset to defaults. This means that if you are looking at many difference dashboards/datasets you have to reselect the option on each navigation. It gets really old. It would be great if those options would persist (local storage?).

**Comment by zeman** [comment]
We persist the options when you're within a team but when you move from one team to another we do reset those. Only some options like number of days can be sticky across teams as all other options could change.

**Comment by okor** [comment]
@zeman I think that maybe the way that teams were originally imagined and the way we are using them differs. They have always felt like a source of friction, not ease. Again, might be the way we are using them. Maybe poke around our account and see what I mean? UX for our setup could definitely be improved.

Anyhow, it's not a bug but maybe something to consider.

**Comment by zeman** [comment]
Within teams the options are preserved but across teams we've decided that only the dashboard will carry across. eg if you're on the "Responsive" dashboard on one team and switch to another then you'll stay on the "Responsive" dashboard.
