### ISSUE TITLE
Please add deep linking

### ISSUE THREAD

**Issue by okor** [SpeedCurve-Metrics/SpeedCurve#95]
It's difficult to share a link with someone because the URL is only part of how data is displayed. I have to share a link and a screenshot/instructions on what options to select. The ability to deep link to some dataset would be great and as is - I consider a bug. Let the URL be the authority on options selected rather than mixing state across URL's, cookies and other things.

**Comment by zeman** [comment]
Can you please provide an example URL. All the options in the dropdown are controlled by the URL. Here's an example from the demo that links to a particular set of options.

https://speedcurve.com/demo/site/?s=302&u=917&b=chrome&r=ap-southeast-2&d=7&share=39tfnozeq94p1o0hndk1kpbg4vb7cg

**Comment by okor** [comment]
@zeman Welp. I can't reproduce now. I, like you, see all the url params and I am able to link directly to the data. Not sure what happened then.

I'd mark this as user error.
