### ISSUE TITLE
Webhook on test completion

### ISSUE THREAD

**Issue by lxfontes** [SpeedCurve-Metrics/SpeedCurve#96]
Use Case: Move test data into a different system ( dashboard / continuous integration ) as soon as test completes. Example:
ci -> deploy -> ping speedcurve -> (test run) -> speedcurve pings back with test results -> update internal metrics

The 2 current workarounds are:
- Set a budget that always trigger.
  Not a good solution as it prevents real budget triggers from being used.
- cron poll every X minutes, keeping last track of last test-id
  Need to keep some state on the other side

**Comment by zeman** [comment]
Rather than checking one of the test_ids use the deploy latest endpoint which gives you the status of all the tests. https://api.speedcurve.com/#lastest-deployment
