### ISSUE TITLE
httpVersion incosistency inside har

### ISSUE THREAD

**Issue by lxfontes** [SpeedCurve-Metrics/SpeedCurve#97]
`har` is reporting invalid/incorrect http versions.

```
$ cat private.har | python -mjson.tool | grep httpVersion | sort | uniq

 "httpVersion": "1.1",
 "httpVersion": ": /",
 "httpVersion": "us:",
```

Expected:
- similar output as chrome ( http/1.1 , h2 )

**Comment by zeman** [comment]
Can you please provide an example of the URL you tested.

**Comment by lxfontes** [comment]
https://wpt.speedcurve.com/export.php?test=160808_X4_b94fe42c5e88e54c1465ec72f9f14180
