### ISSUE TITLE
On 8/15 something broke the ability to use a custom user agent.

### ISSUE THREAD

**Issue by jeffcami** [SpeedCurve-Metrics/SpeedCurve#98]
I use custom user agents for IPhone and IPad such as this Mozilla/5.0 (iPhone; CPU iPhone OS 9_0_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13A452 Safari/601.1 PTST/1 and on 8/15 my user agent was replaced with Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36 under Chrome custom viewport. I cannot update the user agent. I can delete my custom browser config and re-add it but the user agent after saving gets set back to the Windows NT.

This needs to be fixed ASAP as I rely on this for numbers.

**Comment by zeman** [comment]
Hi Jeff, we're looking at this straight away.

**Comment by zeman** [comment]
Jeff, can you please email support@speedcurve.com with the email address you use to login so we can take a look at your account.

**Comment by jeffcami** [comment]
Jeffc@pheinc.com<mailto:Jeffc@pheinc.com>

Sent from my iPhone

On Aug 17, 2016, at 5:33 PM, Mark Zeman <notifications@github.com<mailto:notifications@github.com>> wrote:


Jeff, can you please email support@speedcurve.com<mailto:support@speedcurve.com> with the email address you use to login so we can take a look at your account.

-

**Comment by zeman** [comment]
There was an issue with saving custom UA strings that didn't match known browsers. We sorted that out and you should now be able to update you custom browser to any UA string you like.
