### ISSUE TITLE
Completely wrong stats reported in summary

### ISSUE THREAD

**Issue by okor** [SpeedCurve-Metrics/SpeedCurve#99]
Notice how the first paint is at about 4.5 seconds yet "Start Render" is reported to be 73.4 seconds.

<img width="1238" alt="screen shot 2016-08-18 at 2 47 45 pm" src="https://cloud.githubusercontent.com/assets/142910/17786509/1e48b91c-6553-11e6-9397-14b17172c63e.png">

url: https://speedcurve.com/vox-media/all-brands-no-ads/test/160818_MN_bc9ca62651176199527ffa897e428989/

**Comment by zeman** [comment]
Fixed.
